### ISSUE TITLE
Can glamor do true inline styles?

### ISSUE THREAD

**Issue by ccorcos** [threepointone/glamor#100]
I need a real inline styles solution for building email templates. Is this something thats possible with glamor?

**Comment by threepointone** [comment]
I doubt it :( gmail doesn't take style tags, so that's pretty much a non starter. I'd think plain react `style` prop would be the way it to go?

**Comment by ccorcos** [comment]
Yeah, but I want to render the emails in an online archive as well. So it would be nice to use the same tech in both places. I suppose I could use [`renderStatic`](https://github.com/threepointone/glamor/blob/master/docs/server.md) and then use [juice](https://github.com/Automattic/juice) to inline...

**Comment by ccorcos** [comment]
I think that makes sense...

**Comment by justingreenberg** [comment]
@ccorcos have you checked out https://github.com/revivek/oy?

**Comment by ccorcos** [comment]
hmm. doesnt look like Oy will add vendor prefixes though...
