### ISSUE TITLE
Question: Deleting global rules

### ISSUE THREAD

**Issue by kylpo** [threepointone/glamor#102]
Hey @threepointone, I have a use case where we want to conditionally lock `html` and `body`. I planned to use `styleSheet.insert()` and `styleSheet.delete()` to accomplish this, but I see that `delete` is currently commented out. Is there an alternative way to accomplish this today?

Before switching to Glamor, we used Radium's `<style>` components to conditionally "render" the global styles.

Thanks so much!

**Comment by kylpo** [comment]
related to #59 and commit [bbf75f2](https://github.com/threepointone/glamor/commit/bbf75f26346d67097077cd7bf03aa4a85b9b5691)

**Comment by threepointone** [comment]
I'll probably bring it back, but as a quick workaround, copy paste the deleted functions on to 'StyleSheet.prototype'. That said, I'd like to understand your use case more?

**Comment by kylpo** [comment]
Cool, thanks for your response!

For our use case: we have a web app with scrollable content in the body, and left and right panes that slide into view when activated. When these panes slide in, we want to ensure the user is not able to scroll the content behind, so we lock `html` and `body` using `position: fixed`. For example:
```css
html, body {
    overflow: hidden;
    -webkit-overflow-scrolling: auto;
    position: fixed;
    top: 0;
    width: 100%;
}
```

When a pane is deactivated, we want to rip out the above css to allow the user to scroll again. Sorry, I am not able to share a link to the app - it is an internal one.

**Comment by threepointone** [comment]
it's an interesting usecase, and I might have a solution. imagine, for the sake of this example, that you have a jquery like api to select and add/remove classes
```jsx
let rule = select('html, body', {...})

class Pane extends React.Component{
  onActivate(){
    $('html').addClass(rule)
  }
  onDeactivate(){
    $('html').removeClass(rule)
  }
  render() {
    // ...
  }
}
```

would that work?

**Comment by kylpo** [comment]
That'd be perfect 👌 . Is that available today? If not, please let me know if there is anything I could do to help!

**Comment by threepointone** [comment]
yes, `select` exists(`import { select } from 'glamor'`), though you'll have to make your own `$` / `addClass` / `removeClass` helpers.

**Comment by kylpo** [comment]
Excellent! Didn't see that `select()` returns a className. I'll give it a go later today and close this out if it works. Thanks!

**Comment by threepointone** [comment]
closing, feel free to reopen if you have a problem

**Comment by PopeOnARope** [comment]
I have a similar use case, but I need be able to add and delete `@import` statements on the fly.  Is there a built in way to do this? We are using `insertRule` with success, but we need to be able to delete rules as well to avoid having a bunch of duplicates.

Thanks!
