### ISSUE TITLE
jest snapshots

### ISSUE THREAD

**Issue by chrisdrackett** [threepointone/glamor#104]
Has anyone used glamor when using jest snapshot testing?

**Comment by kentcdodds** [comment]
I think this would be a real winner for testing. Here's something I think would be super cool. Take this as an example:

```javascript
import React from 'react'
import {style, compose, hover} from 'glamor'
import THEME from '../lib/styles/theme'
const container = style({ color: THEME.primary })
const item = compose({ backgroundColor: '#ccc' }, hover({ backgroundColor: 'white' }))
const selected = style({ fontWeight: 'bold' })

export default SomeUI

function SomeUI() {
  return (
    <div {...container}>
      <ul>
        <li {...item}> one </li>
        <li {...item} {...selected}> two </li>
        <li {...item}> three </li>
      </ul>
    </div>
  )
}
```

I'd love to be able to do this in my tests:

```javascript
import React from 'react'
import {render} from 'enzyme'
import {renderToJson} from 'enzyme-to-json'
import {setupForTests} from 'glamor'
import SomeUI from './some-ui'

setupForTests() // <-- magic function I made up

test('renders', () => {
  const wrapper = render(<SomeUI />)
  expect(renderToJson(wrapper)).toMatchSnapshot()
})
```

And this could result in a snapshot like this (beware, snapshot hand-crafted, could be inaccurate, but I think it should give you an idea):

```
exports[`test renders 1`] = `<div
  data-css-blahblah={
    Object {
      "color": "#0000ff",
    }
  }>
  <ul>
    <li
      data-css-blahblah2={
        Object {
          "backgroundColor": "#ccc",
        }
      }
      data-css-hover-blablah2={
        Object {
          "backgroundColor": "white",
        }
      }> one </li>
    <li
      data-css-blahblah2={
        Object {
          "backgroundColor": "#ccc",
        }
      }
      data-css-hover-blablah2={
        Object {
          "backgroundColor": "white",
        }
      }
      data-css-blahblah3={
        Object {
          fontWeight: 'bold',
        }
      }> two </li>
    <li
      data-css-blahblah2={
        Object {
          "backgroundColor": "#ccc",
        }
      }
      data-css-hover-blablah2={
        Object {
          "backgroundColor": "white",
        }
      }> three </li>
  </ul>
</div>
`;
```

What would be cool about this is now I could see when my styles change across my app when I make changes to my shared CSS in JS objects. That would be preeeeetty slick.

**Comment by threepointone** [comment]
how about snapshotting the generated css instead of the whole render tree? it would look something like 
```jsx
let { styleSheet, flush } = require('glamor')

flush() // call this before every test
// ...do some rendering
expect(styleSheet.rules()).toMatchSnapShot() 
```

**Comment by kentcdodds** [comment]
Hmmmm... Perhaps. I guess that's a start. But I'd really like to see the styles for an element right next to the element in the snapshot rather than having to associate class names

**Comment by threepointone** [comment]
is there a way to hook into renderToJson? for your idea to work, you need to process every node, pull out data attributes and classnames which are glamor-like, and copy the json in.

**Comment by kentcdodds** [comment]
Hmmm... what if instead it was:

```javascript
renderToJson(applyStylesInline(wrapper))
```

? The trouble here is `wrapper` is an enzyme-specific thing, but I'm pretty sure there's a way to get ahold of and manipulate the dom node it's wrapping. Then you could just query it and replace all the matching styles... maybe? 🤔💭  :)

**Comment by threepointone** [comment]
not sure there's anything I can do from my side? 
ps - how good is jest for browser based testing? If you have a look at my tests and my karma conf, is it possible for me to move to jest?

**Comment by kentcdodds** [comment]
Yeah, I'm starting to think that the most reasonable thing to do would be to flush as you said. I wonder if there's a way we could write a plugin for react-storybook so storyshots would add glamor styles to the storyshot snapshot. I'll bet it's possible.

Jest does not really do browser-based testing. I don't think that it's really in the future plans either. Out of scope for the project I think.

**Comment by kentcdodds** [comment]
I'm trying the `styleSheet.rules()` thing and getting back a `CSSStyleRule`. If I try to `toString` that I get `[object CSSStyleRule]` and if I try to `JSON.stringify` it I get `{}`. Inspecting the object gives me a bunch of stuff that I don't want in a test like this. Is there a way that I can get _only_ the styles?

**Comment by threepointone** [comment]
are you running this in a browser? `CSSStyleRule` only shows up there.

**Comment by kentcdodds** [comment]
Yeah, I was testing things out in the browser.

**Comment by kentcdodds** [comment]
But I just tried it out in the node repl and it looks like this will be perfect:

```
~/Developer/react-github-profile (master)
👻  $ node
> var glamor = require('glamor')
undefined
> glamor.style({padding: 10})
{ 'data-css-1qbd000': '*' }
> glamor.styleSheet.rules()
[ { cssText: '.css-1qbd000,[data-css-1qbd000]{padding:10px;}' } ]
```

**Comment by kentcdodds** [comment]
Though... Hmmm... Should probably figure out a way to format that.

**Comment by kentcdodds** [comment]
Ah, just realized that this wont work out if you've got jsdom simulating a browser environment, which most of the time you will... :-(

**Comment by threepointone** [comment]
try `styleSheet.rules.map(x => x.cssText)`

**Comment by threepointone** [comment]
(That *should* work on both browser/server/jsdom)

**Comment by threepointone** [comment]
anything I need to do here further? Lemme know, else I'll close the issue. Cheers!

**Comment by kentcdodds** [comment]
It does print out the string, but the string isn't formatted so the snapshot diff will be pretty bad. I wonder if there's a package to format a CSS string 🤔

**Comment by threepointone** [comment]
Tons, lol https://www.npmjs.com/search?q=css+beautify

**Comment by kentcdodds** [comment]
I feel like last time I looked through that list, they all transform files, none expose APIs to beautify strings :-(
Maybe I need to look closer

**Comment by threepointone** [comment]
this has been solved by the incredible kent in https://www.npmjs.com/package/jest-glamor-react, closing this issue
