### ISSUE TITLE
Glamor customizing common components best practices.

### ISSUE THREAD

**Issue by mikedklein** [threepointone/glamor#105]
This isn't really an issue with glamor more a question on what best practices would be if I have a common UI component that I may want to allow for additional customization: 
```jsx
import React, { PropTypes } from 'react'
import { style } from 'glamor'

const sectionStyle = style({
  minHeight: 500,
  width: '100%',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center'
})

const Section = (props) => {
  let className = sectionStyle
  // Here is where I am not sure if this is the best way to go about this
  if (props.className !== undefined) {
    className += ` ${props.className}`
  }

  return (
    <section className={className}>
      {props.children}
    </section>
  )
}

Section.propTypes = {
  children: PropTypes.element,
  className: PropTypes.object
}

export default Section
```

So if in another component I want to add a background:

```jsx
const sectionStyle = style({
  background: 'url("http://i3.kym-cdn.com/photos/images/original/000/546/077/689.jpg") center',
  backgroundSize: 'cover'
})

class App extends Component {
  render () {
    return (
      <div className='App'>
        <Section className={sectionStyle}>
          <h1>Section 1</h1>
        </Section>
      </div>
    )
  }
}

export default App
```

Is this the best way to go about making components like this? Should I be using merge? Thanks for any clarification.

**Comment by threepointone** [comment]
There are a number of ways you can achieve this; in general I believe in leaving this up to the consumer. 
- to augment the above, you could accept classNames, pull out the ones that are glamor-like (they have a pattern `.css-<id>` and `merge` them before applying them again. This would give you predictable precedence order 
- you could accept a `css` prop separate of classnames, and merge that instead.

**Comment by mikedklein** [comment]
@threepointone awesome thanks!
