### ISSUE TITLE
Incorrect parsing of overriden, dashed properties

### ISSUE THREAD

**Issue by jalooc** [threepointone/glamor#106]
Parsing a dobule-word (dashed) property with overriden values emits proper name only for the first of the array values.
![image](https://cloud.githubusercontent.com/assets/6209244/20041397/9e00201a-a468-11e6-8f02-857ac66dfc37.png)

On the other hand, specifying the property name in the style object with dash works correctly, but throws an "unsupported property" warning
![image](https://cloud.githubusercontent.com/assets/6209244/20041435/5336805a-a469-11e6-811f-83e5c7ee6532.png)
![image](https://cloud.githubusercontent.com/assets/6209244/20041448/7b20f564-a469-11e6-802e-b0b64c3b8bf6.png)

**Comment by threepointone** [comment]
noted, will fix

**Comment by threepointone** [comment]
this should be fixed and live in 2.18.0.
