### ISSUE TITLE
global variables ?

### ISSUE THREAD

**Issue by sylvainbannier** [threepointone/glamor#108]
I'm trying to convert some CSS files to glamor syntax.

Currently I use CSS3 variables to define some common rules and calc to adapt thoses variables to my components context

```
#variables.css
:root {
--gutter: 1rem;
}

#myComponent.css
.myComponent {
margin:calc(var(--gutter) / 2)
}
```
I'm struggling to find a good way to translate that in glamor API.

So far I do things like that :

```
#variables.js
export const gutter = 1;

#myComponent.js`
import {gutter} from 'variables.js';
const style = css({
  margin:(gutter * 2) + 'rem'
});
```
But I'm not satisfied with the `+'rem'` part and the lack of unit in `gutter` definition.

Am I doing it wrong ? is there a better way ?

**Comment by mikedklein** [comment]
@sylvainbannier I am not sure this is better, but I usually do all that in my variables file (assuming that you reusing that margin a lot:
```
#variables.js
const GUTTER_VAL = 1
const MARGIN_VAL = GUTTER_VAL * 2

export const margin = `${MARGIN_VAL} rem`

#myComponent.js
import { margin } from 'variables.js'
import { style } from glamor

const styles = style({
  myComponentStyle: {
    margin
  }
})
```

**Comment by threepointone** [comment]
there's a helper for 'vars' aided by react - https://github.com/threepointone/glamor/blob/master/docs/vars.md 
I have a full fledged example under [examples/tweet](https://github.com/threepointone/glamor/tree/master/examples/tweet) (an implementation of https://github.com/styled-components/comparison)

now, I don't have a good answer for the `rem` issue. Open to ideas; wondering what a plugin for the same would look like.

**Comment by sylvainbannier** [comment]
`vars` seems well suited for discrete values, but in my case I need to compute thoses values *then* append the unit.
Perhaps I don't get it but it seems that in https://github.com/threepointone/glamor/tree/master/examples/tweet there all sizes are statically defined (ex: https://github.com/threepointone/glamor/blob/master/examples/tweet/app.js#L33).

**Comment by threepointone** [comment]
yeah I see the problem, haven't thought of a clean enough solution though. 
- maybe a `calc()` helper?
- native `calc` has pretty wide support, maybe something like margin: `calc(${vars.gutter} /2)` would do the trick?

**Comment by sylvainbannier** [comment]
That what I used to do. But `calc` support is not as wide as I'd like : 
http://caniuse.com/#search=calc (around 80%). That's why I was trying to replace it with js variables.

**Comment by threepointone** [comment]
so do you suppose a `calc()` helper would solve your problem? 
```jsx
margin: calc(`${vars.gutter} /2`)
```
just an idea, of course. open to implementations/ PRs as well :)

**Comment by sylvainbannier** [comment]
Yes I think so. Except for UC browser but who cares :) ?

thanks all.
