### ISSUE TITLE
typescript/flow annotations

### ISSUE THREAD

**Issue by threepointone** [threepointone/glamor#11]
once the hairball is refactored, must consider adding flow and/or ts typings to the lib. because apparently that's a thing now. 

keeping this issue open for the same. please contribute!

**Comment by donaldpipowitch** [comment]
TS would be awesome ♥

**Comment by kushalpandya** [comment]
Will try to add `d.ts` on this, see how it goes.

**Comment by donaldpipowitch** [comment]
`.d.ts` files are added by now (e.g. https://github.com/threepointone/glamor/blob/master/index.d.ts).

**Comment by pbomb** [comment]
I'd be interested in adding Flow typings. I'll see if I can find the time.

**Comment by pbomb** [comment]
I'm curious what you're looking for, implementation-wise, with Flow. Would you like to see Flow types inline with the code, or just declaration files that describe the external API?

**Comment by otbe** [comment]
+1 for declaration files :)

**Comment by aziz** [comment]
Any update on flow types?

**Comment by threepointone** [comment]
closing this for now, will revisit in a new issue regarding v3 plans.
