### ISSUE TITLE
Method of defining styles

### ISSUE THREAD

**Issue by rt2zz** [threepointone/glamor#114]
First question: is the recommendation to create styles as a file singleton, as a class property, or in render?
```js
// file singleton
class Foo extends Component { /*...*/ }

const fooStyle = style({/*...*/})

// class property
class Foo extends Component {
  fooStyle = stryle({/*...*/})
  // ...
}

// in render
class Foo extends Component {
  render() {
    return <div {...style({/*...*/}) />
  }
}
```

We have so far gone the file singleton route, but as seeing major performance cost to initializing all styles before first render. We are in the process of code splitting aggressively to resolve the initial load cost, but I am simultaneously curious if there are any techniques for deferred rendering, especially in cases where flash of unstyled content may be acceptable.

**Comment by threepointone** [comment]
Are you compiling with NODE_ENV=production? I might have had a perf regression, will check. 

There's no specific recommendation right now, as you can imagine it's on a case by case basis. I've personally been attaching styles to classes, but mixing it up as I write the app.

**Comment by rt2zz** [comment]
Production makes the run time acceptable, but still non trivial (will need to dig in further to get profiling numbers).

In dev however we are looking at 10s of additional initial processing time which makes  dev a bit tedious.

Will report back with additional findings, in the meantime we might go the class property route.

**Comment by threepointone** [comment]
If it helps, you can trigger production perf with the following snippet 
```jsx
import { speedy } from 'glamor'
speedy(true)
```

include this as the first line of your app. the drawback is that the styles are visible but not editable in devtools, which might be a worthy tradeoff for your scenario.

Can you tell me more about your app? ~ how many styles/ rules do you have? is there an opportunity to prerender/SSR CSS? happy to help.

**Comment by threepointone** [comment]
another option (and this is a hack) is this snippet - 
```jsx
import { styleSheet } from 'glamor'
styleSheet.maxLength = 1000
```
this doesn't have the previous drawback. maxLength defaults to 65k for most browsers, but feel free to adjust this number.

**Comment by rt2zz** [comment]
if maxLength = 1000, what happens with the 1001'st style rule?

**Comment by threepointone** [comment]
internally, glamor makes a new style tag and append to that. should not affect you, but it matters for older IE edgecases with sites with many thousands of rules. you *should* be fine.
