### ISSUE TITLE
simulate media queries ?

### ISSUE THREAD

**Issue by sylvainbannier** [threepointone/glamor#125]
Is it possible to simulate media queries ? I found no evidence of this in source code : 
just a skipped test in travis https://travis-ci.org/threepointone/glamor/builds/148275309
`can simulate media queries (skipped)`

**Comment by threepointone** [comment]
It should be *possible*, I haven't gotten around to it tho.

**Comment by threepointone** [comment]
actually, I can't think of a way to do this cleanly. but now that nesting of arbitrary rules is possible, it should be simpler to design in isolation, and then wrap with a media query. closing for now, lemme know if you need anything. removing the stub test too.

**Comment by sylvainbannier** [comment]
I think I may have the wrong approach to this issue. I should focus on container size adaptation rather than media queries
