### ISSUE TITLE
real css kills flowtype and whole idea of code > string

### ISSUE THREAD

**Issue by steida** [threepointone/glamor#126]
https://github.com/styled-components/styled-components/issues/256#issuecomment-262858458

**Comment by threepointone** [comment]
closing this in favor of the SC issue.

**Comment by steida** [comment]
@threepointone There is dubious silence about that. As I think about it, what we need is typed-styles, not styled-components. I started on the prototype already. Btw, why glamor doesn't use style elements in body collocated within elements itself? It's supported by browser engines, auto-reconciled with React, did I overlook something? Thank you!
