### ISSUE TITLE
glamor/aphrodite - How to edit output classNames?

### ISSUE THREAD

**Issue by Hazantip** [threepointone/glamor#129]
Usually i getting classNames on output like this - `css-bcq9c7`, but it's very hard to debug in browser devtools, is it possible to **change** somehow classNames for example replace`css-`, to className which i applied to this element?

**Comment by threepointone** [comment]
this is a common request, but there's no first class way right now. I have some documentation incoming on how to use data attributes + labels to get some of this functionality back, will leave this issue open till then.

**Comment by Hazantip** [comment]
Ok, how to use data attributes, labels to pass my classNames to elements, like  ׳<div className="css-hxufuf" data-origin-class="containter" />

**Comment by Hazantip** [comment]
Ok, how to use data attributes, labels to pass my classNames to elements, like
`<div className="css-hxufuf" data-origin-class="containter" />`

**Comment by threepointone** [comment]
let me clarify. so, style objects can be 'applied' as props instead of classnames, like so -
```jsx
let rule = style({ 
  color: 'red'
})
// these 2 are equivalent
<div className={rule}>...</div>
<div {...rule}>...</div>
```
 and they also accept a special property 'label', so you can do this - 
```jsx
let rule = style({
  color: 'red',
  label: 'error'
})
// ...
<div {...rule}> ... </div>

// and it'll appear in your html as 
<div data-css-125aujn="error"> ... </div>
```
this also works when merging styles
```jsx
let error = style({
  color: 'red',
  label: 'error'
})

let big = style({
  fontSize: '20',
  label: 'big'
})

// and when rendering -
<div {...merge(error, big)}> ... </div>

// appears as
<div data-css-1adfy4z="[error + big]"> ... </div>
```

I'll write proper documentation for this soon, but I hope this helps.

**Comment by Hazantip** [comment]
@threepointone, thank you, but I didn't try yet what you typed, because that not exactly what i need. =/ 
Your solution require to refactor all my project, but he is huge.. I tying to figure out how apply some changes inside glamor/aphrodite to get in output readable class names, or even add some additional attribute like `data-origin-classname="myClass"`

**Comment by threepointone** [comment]
I understand. fwiw, I'm working on an enhancement where these labels should show in the css sidebar as well, maybe that'll make it better?

**Comment by threepointone** [comment]
labels now show in the sidebar too. closing this for now, lemme know if you have other ideas.

**Comment by Hazantip** [comment]
unfortunately we didn't get an answer for this topic ;(

**Comment by threepointone** [comment]
because the labels are the most I can do for now. being able to output readable classnames is important to me, but it goes against the design of the lib right now, and will require major refactoring. the hashing is important for deduping and composition, so can't break that yet. I might well get back to this in the future, but nothing just yet, unless you have some ideas on how to achieve it?

**Comment by Hazantip** [comment]
'how to...' i don't know unfortunately. Thanks.

**Comment by threepointone** [comment]
I'm sorry, I understand it's not a satisfying answer, but it's the best I have right now. I hope to make it better soon.
