### ISSUE TITLE
Styles in head but not rendered in Component

### ISSUE THREAD

**Issue by abhiaiyer91** [threepointone/glamor#132]
Hello!

I just started using Glamor, converting from Aphrodite and was looking to take advantage of the aphrodite shim. In my React Storybooks, everything is working properly, but when I render in my app that mixes (css and css-in-js) I see that my components have the className hash (`css-foo`) and can find the same hash in the `style` tag on Head, but the styles aren't rendered in my component!

So then I tried the normal `style()` api and everything worked. 

Any idea what my problem could be?

**Comment by threepointone** [comment]
Not sure exactly. Do you have a gist / sample code?

**Comment by abhiaiyer91** [comment]
Sure!

Here's the component

```
import { style, merge } from 'glamor'
import { css, StyleSheet } from 'glamor/aphrodite';

const styleSheet = style({
  color: 'blue',
});

const aphroditeStyle = StyleSheet.create({
  title: {
    color: 'red',
    fontWeight: 'bold',
  },
  subtitle: {
    textAlign: 'center',
  },
});

function HelloWorld() {
  return (
    <div>
      // does work
      <p className={aphroditeStyle.title}>Hi</p>
     // does not work
      <p className={css(aphroditeStyle.title)}>Hi</p>
      // does not work
      <p className={css(aphroditeStyle.title, aphroditeStyle.subtitle)}>Hi</p>
      // works
      <h1 className={styleSheet}>Hello World</h1>
    </div>
  );
}
```

**Comment by abhiaiyer91** [comment]
Seems like the merge function is the culprit! But doesn't make sense why everything would work in a storybook

**Comment by threepointone** [comment]
your code seems to work for me. also this seems to be errant?
```jsx
const styleSheet = style({
  color: 'blue',
});
```

**Comment by threepointone** [comment]
please try the latest version

**Comment by abhiaiyer91** [comment]
After upgrading, glamor is throwing an error here

https://github.com/threepointone/glamor/blob/fdd60d7f3075a95cdf638d207a1f8f58b710309a/src/autoprefix.js#L11

`Uncaught TypeError: obj.indexOf is not a function`

Possibly something messed up in a css function somewhere?

**Comment by threepointone** [comment]
Can you tell me what style threw that error?

**Comment by abhiaiyer91** [comment]
Ah okay this was the error (probably left over syntax from our aphrodite setup)
```
var opacityFadeIn = {
  'from': {
    opacity: 0,
  },
  'to': {
    opacity: 1,
  },
};

var foo = StyleSheet.create({
  animationName: opacityFadeIn,
  animationDuration: '2s',
});
```

**Comment by threepointone** [comment]
yeah, the aphrodite shim doesn't handle animations and fonts in a fully compatible way. I'll try to get a better error message in, cheers. all else working for you?

**Comment by abhiaiyer91** [comment]
Yes we are in business! Thank you!!

**Comment by threepointone** [comment]
cheers, let me know if I can help you with anything else.
