### ISSUE TITLE
Compiled names are too different than the provided inline styles

### ISSUE THREAD

**Issue by bernardoatworkpop** [threepointone/glamor#135]
I am using the the aphrodite style to define some of the style classes for my component (we recently switched from aphrodite), but glamour seems to change their names when compiling the stylesheet, which makes it harder to debug.

For example, the following aphrodite-like style:

```
const styleSheet = StyleSheet.create({
 messagePaginator: {
    margin: 16,
    display: 'flex',
    [tabletScreenMedia]: {
      margin: '16px 10px',
    },
```

Which I use in this component:

```
<Paginator page={activePageIndex} pageCount={pageCount} pageClick={onPageClick} className={css(styleSheet.messagePaginator)} />}
```

Is renamed to something like:

```
<div class="css-yj59ol">
```

If we could prefix the compile css name to what is provided in the styleSheet key, the problem would be fixed (e.g., css-messagePaginator-yj59ol)

**Comment by threepointone** [comment]
this is a commonly asked question, and I want to get to it, but it'll require a massive refactor (and I can't even figure out a clean way yet). https://github.com/threepointone/glamor/issues/129#issuecomment-263205730 using labels is the recommended way for now. if the rule is used as a data-attribute, they'll show inline, but will also show in the sidebar whether classname/data-attr.

**Comment by milesj** [comment]
Somewhat related, but I've been working on a React HOC style abstraction layer known as Aesthetic (https://github.com/milesj/aesthetic). Glamor is supported as one of the adapters, and I prefix all Glamor class names with the name of the component, which would solve this use case.

**Comment by jmca** [comment]
In my Glamor projects (using React in this case) I use this little util function (or variation of it) to add labels generated from prefix+keys. It's not crazy robust as it is but enhance at will.

```
function lbl(styles = {}, prefix = '', tether = '_') {
  styles = Object.assign({}, styles)
  Object.keys(styles).forEach(key => {
    styles[key] = Object.assign({}, styles[key], {
      label: `${prefix}${tether}${styles[key].label || key}`
    })
  })
  return styles
}

```

```
// Style Map
const styles = lbl({
  style1: {color: 'red'},
  style2: {color: 'green'},
  style3: {color: 'red'}
}, SomeComponent.displayName)

// In render method
<div {...css(styles.style1)}>...
<div {...css(styles.style2)}>...
<div {...css(styles.style3)}>...

// Outputs
<div data-css-loaw01="SomeComponent_style1">...
<div data-css-1ij12ax="SomeComponent_style2">...
<div data-css-1srekji="SomeComponent_style3">...
```
