### ISSUE TITLE
Probably breaking change without updating semver major.

### ISSUE THREAD

**Issue by jalooc** [threepointone/glamor#138]
![image](https://cloud.githubusercontent.com/assets/6209244/20795574/24b8ad80-b7d2-11e6-8527-51fd81654967.png)

This error showed up after running `npm i` with package locked up on major version: `"glamor": "^2.17.14",`. It seems that you removed the `fontFace` method from `'glamor'` exports and replaced the usage with `css.fontFace` without updating major semver version.

**Comment by threepointone** [comment]
yeah that was my bad. I've since brought it back though, what version are you on?

**Comment by jschr** [comment]
hey, same issue here when installing the latest from npm which appears to be 2.20.8

**Comment by jalooc** [comment]
`2.20.8` installed in `node_modules`

**Comment by threepointone** [comment]
I'll check and fix this today. sorry!

**Comment by threepointone** [comment]
could you folks check 2.20.9?

**Comment by threepointone** [comment]
closing this, feel free to reopen if it happens again.
