### ISSUE TITLE
Placeholder selector is not vendor prefixed

### ISSUE THREAD

**Issue by eldh** [threepointone/glamor#14]
It seems placeholder styles are not working in Chrome, seemingly because the selector `::placeholder` is not supported (needs to be `::-webkit-input-placeholder`) and as far as I could tell from a quick look through the code, the selectors are not processed by the prefixer, only rules are.

Question is, since the cases where the selector needs to be prefixed somehow are quite rare and tricky to handle in a generic way (for example, to get placeholder styling to work cross-browser you need to duplicate the rule blocks iirc), is it better to handle these things case by case or find some more generic solution (i.e pass all selectors through a prefixer)?

**Comment by threepointone** [comment]
Good catch, I didn't know this. I should be able to add it. As a workaround for now, try this undocumented method - `add(':-webkit-input-placeholder', style)` (note the single colon, not double)

**Comment by eldh** [comment]
Cool! I ended up with this: 

```js
const placeholder = (x) => ({
  ...add(':placeholder', x),
  ...add(':-webkit-input-placeholder', x),
  ...add(':-moz-placeholder', x),
  ...add(':-ms-input-placeholder', x),
})
```

**Comment by threepointone** [comment]
✌️

**Comment by threepointone** [comment]
the next version of glamor should do this automatically

**Comment by jaydenseric** [comment]
Placeholder is still not vendor prefixing:

```
import React from 'react'
import {css} from 'glamor'

const styles = {
  '::placeholder': {
    color: 'red'
  }
}

export default () => (
  <input className={css(styles)} placeholder='Test' />
)
```

Results in this output in the head stylesheet:

```
.css-f6kjmy::placeholder,[data-css-f6kjmy]::placeholder,.css-f6kjmy[data-simulate-placeholder],[data-css-f6kjmy][data-simulate-placeholder]{color:red;}
```

**Comment by threepointone** [comment]
ah, it doesn't do it for the nested version, only when using the helper. will fix.

**Comment by threepointone** [comment]
fixed in 2.20.14

**Comment by fhelwanger** [comment]
It isn't working right now.

Glamor put all vendor prefixes in a single comma separated rule: https://github.com/threepointone/glamor/blob/09dd49dac0ca7c96c45da4dad420ece6e82379de/src/index.js#L322-L325

But it doesn't work. I found why here: http://stackoverflow.com/a/23338422/2379685

> ...if any selector in your comma separated list is not recognized by your browser, it skips the whole rule and goes on to the next.

You can test it in this fiddle using chrome:

https://jsfiddle.net/Lcjfkrb2/

Also, you can go to https://autoprefixer.github.io/ and paste:

```css
input::placeholder {
  color: red
}
```

The result will be:

```css
input::-webkit-input-placeholder {
  color: red
}
input::-moz-placeholder {
  color: red
}
input:-ms-input-placeholder {
  color: red
}
input::placeholder {
  color: red
}
```

Couldn't this be handled by autoprefixer instead of hard coded?

**Comment by fhelwanger** [comment]
Done!
