### ISSUE TITLE
insertRule() should carefully handle @imports

### ISSUE THREAD

**Issue by otbe** [threepointone/glamor#142]
Hi @threepointone,

```@impot url()``` rules must be the first entries in every stylesheet. So I think insertRule should handle it properly (prepending instead of appending :)).

Example
```
insertRule(`html{font-size: ${defaultFontSize};}`);
insertRule('@import url(https://fonts.googleapis.com/css?family=Merriweather+Sans:300,300i,400,400i|Merriweather:300,300i,400,400i|Lato:300,300i,400,400i,700,700i);');
```
UseCase: in some common modules we define this import, but we can not guarantee that it will be executed in a proper order.

**Comment by threepointone** [comment]
hmm good idea, I'll get to this.
