### ISSUE TITLE
What's the difference between `css` and `style`?

### ISSUE THREAD

**Issue by cellis** [threepointone/glamor#144]
I'm reviewing the docs and I see references to 2 methods: `css` and `style`. Is there any difference?

Also, I'm trying to use an external css lib, like bootstrap or flexboxgrid. Is there a way to integrate classes from those libraries like this:

```html
<div className={"row" + <glamor-expression>}>
</div>
```

**Comment by threepointone** [comment]
There's no difference between the two. I'm keeping style() around for legacy reasons. 

Your example for integrating classes looks fine, tho you need a space after row - "row " + <glamor-expr>

**Comment by cellis** [comment]
I figured out that

```
<div className={"row"} {...css({...})}>
</div>
```
Also worked. This seems cleaner.

**Comment by threepointone** [comment]
Yes, that's my preference too :) closing this for now, lemme know if you have any more issues
