### ISSUE TITLE
Get calculated values

### ISSUE THREAD

**Issue by bluetidepro** [threepointone/glamor#147]
If I have something like this following:

```js
    const containerStyles = merge(ButtonStyle.container, style.container);
    let calculatedBorderColor = containerStyles.backgroundColor;
```

Is it even possible to get a calculated value from `containerStyles`? I'm having problems trying to get anything from that after glamor merges it. That `const` doesn't show the values from the `merge`. **Is it possible to get the calculated styles somehow?**

(By the way, love the project! Keep up the great work!)

**Comment by threepointone** [comment]
you could apply it on an element? there's also `cssFor(rule)` that should generate the css for the given rule. can you tell me about your specific usecase?

**Comment by threepointone** [comment]
closing this for now, lemme know if something comes up.
