### ISSUE TITLE
Proposal: Use atomic css rules

### ISSUE THREAD

**Issue by danielberndt** [threepointone/glamor#148]
I just stumbled upon [this article](https://ryantsao.com/blog/virtual-css-with-styletron) and was quite impressed by their approach and their performance numbers. 

As I feel that glamor strives to combine all the best css-in-js ideas out there into one awesome package, I'm wondering how you feel about this idea of using atomic style rules?

**Comment by jessehart** [comment]
+1 for stealing some of these ideas! Great article.

**Comment by AndrewIngram** [comment]
Styletron is a more low-level API, so another question might be about whether Glamor can use it behind the scenes and focus on the friendly API side of things.

**Comment by threepointone** [comment]
Closing this issue for now, not much that's actionable here per se.

**Comment by danielberndt** [comment]
Sorry for the rather vague ticket. 

To be more concrete about what type of performance I'm interested in: byte size of the stylesheet when server-side rendering. There's the magical number of delivering html and css within the first 14KB to guarantee that something meaningful can be rendered with the first http package.

So using something like atomic css to (ideally) find the smallest possible combination of rules (which I guess is a NP-hard problem) would probably help here. But I also thing that gzip will probably replicate a lot of what atomic css is attempting anyways.

I'll open a new issue once we have some hard data showing the potential benefits of atomic css :)

**Comment by threepointone** [comment]
Glamor already exposes renderStaticOptimized to give you just the css required for the given page. You could try algorithms on that chunk if you want to optimize further. 

That said, glamor already performs fairly well via gzip. Lemme know if you find anything new!
