### ISSUE TITLE
"__webpack_require__.i(...) is not a function" introduced with 2.20.0

### ISSUE THREAD

**Issue by donaldpipowitch** [threepointone/glamor#149]
Disclaimer: I'm not sure if this is a problem with glamor or webpack yet, but I'll create this issue to make my progress public. Maybe this helps someone.

When switching from `2.19.0` to `2.20.x` my build apps throw an error: `_webpack_require__.i(...) is not a function`.

Looking at the source code it happens here:
```
__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0_glamor__["fontFace"])({
```

It doesn't throw for `2.19.0`.

I _think_ it happens only for apps build with `webpack@1` as I don't see this error for newer apps created with `webpack@2-beta`. I'll try to create a minimal test case.

Screenshot from the debugger:

![image](https://cloud.githubusercontent.com/assets/1152805/20961721/94c82932-bc66-11e6-9d31-a2d972fca0ce.png)

It looks like everything is defined there except `fontFace`. 

Fixed it. Pull request is coming.

**Comment by threepointone** [comment]
published in 2.20.13
