### ISSUE TITLE
glamor.fontFace is undefined

### ISSUE THREAD

**Issue by frontsideair** [threepointone/glamor#152]
I was importing `fontFace` directly from `glamor` like this: `import { fontFace } from glamor` at version `2.15.6` but when I upgraded to `2.20.12` it stopped working. I checked the apidoc and saw it under `css` and fixed it. But I was also using `keyframes` and it wasn't broken. I [checked the code](https://github.com/threepointone/glamor/blob/master/src/index.js#L447-L461) and looks like `keyframes` is defined before export but `fontFace` is defined after it.

Since the solution is obvious I may send a PR if you think fixing is okay to keep it more backwards compatible.

**Comment by threepointone** [comment]
just pulled in a fix for it, https://github.com/threepointone/glamor/pull/151 
working on another bug, once that's done I'll do a release, probably tomorrow

**Comment by frontsideair** [comment]
Looks like #149 was the same as this one. Fixed by #150.
