### ISSUE TITLE
IE11 Object Assign support

### ISSUE THREAD

**Issue by abhiaiyer91** [threepointone/glamor#155]
Hey there @threepointone, hope youre doing well.

Was just about to deploy my app to production and ran into an error in IE11

"No assign method on Object"

Then i looked into the project and saw glamor does not provide a transform, or runtime transform? Is there a reason for this? is there something I need to do in my app besides polyfill myself?

**Comment by ChristopherBiscardi** [comment]
@abhiaiyer91 you should likely be including your own Object.assign polyfill here (such as [babel-polyfill](http://babeljs.io/docs/usage/polyfill/)). This is also true [historically](https://github.com/babel/babel/issues/377) with the babel project which glamor [is using](https://github.com/threepointone/glamor/blob/master/.babelrc) for compilation.

**Comment by arunoda** [comment]
Guys, here's the fix: https://github.com/threepointone/glamor/pull/166
Hope we can have a release soon with the fixed `lib` files.

**Comment by threepointone** [comment]
published in 2.20.13, lemme know if this works.

**Comment by arunoda** [comment]
@threepointone Thanks a lot.
It works.
