### ISSUE TITLE
How to use with Shadow DOM

### ISSUE THREAD

**Issue by treshugart** [threepointone/glamor#16]
Since glamor mutates a stylesheet in the head - I don't see any options how to suppress that and instead generate a string or use an alternate style tag - I'm wondering how this could be used to work with a style tag in a shadow root since global styles can't leak into a shadow root?

A way to do this might be to buffer the calls and return a string:

```js
import { buffer, style } from 'glamor';

const div = document.createElement('div');
const css = buffer(() => {
  return {
    declaration1: style({ backgroundColor: 'orange' }),
    declaration2: style({ backgroundColor: 'black' }),
  };
});

div.attachShadow({ open: true });
div.shadowRoot.innerHTML = `
  <style>${css.toString()}</style>
  <div ${css.declaration1}>
    <span ${css.declaration2}>in shadow root</span>
  </div>
`;
```

I've thought about being able to supply a custom style element, however, that would couple the implementation to the actual DOM and in my case, I'm using web components with a virtual DOM.

**Comment by threepointone** [comment]
good q, I don't have a strong answer for this right now, not too familiar with shadow dom etc. I'll read up; do you have any links I could read?

**Comment by treshugart** [comment]
Safari has a good writeup of the v1 API being released in Safari 10 and Chrome 53. https://webkit.org/blog/4096/introducing-shadow-dom-api/. A good cheat sheet is http://robdodson.me/shadow-dom-css-cheat-sheet/. 

Basically, you must create a <style> tag in your shadow root in order to style elements within it. The only things that cross the shadow boundary are inherited things like font-family and the like.

**Comment by threepointone** [comment]
would a `cssFor(rule)` helper, um, help? so you could `merge()` the rules you want, take the literal css, and then do as you please. because of the way we hash rules etc, it shouldn't cause issues if it's in main document head.

**Comment by treshugart** [comment]
That could possibly work. What would an expanded API look like for it?

**Comment by threepointone** [comment]
something like this, let's say - 
```jsx
import { cssFor, idFor, style } from 'glamor';

const div = document.createElement('div');
let orange = style({ backgroundColor: 'orange' })
let black = style({ backgroundColor: 'black' })

div.attachShadow({ open: true });
div.shadowRoot.innerHTML = `
  <style>${cssFor(orange, black)}</style>
  <div ${idFor(orange)}>
    <span ${idFor(black)}>in shadow root</span>
  </div>
`;
```

**Comment by treshugart** [comment]
That would be awesome.

**Comment by treshugart** [comment]
Would be nice if `idFor()` could accept multiple arguments and return an object so it'd work with `{...idFor(orange, black)}`.

**Comment by threepointone** [comment]
while I could do that, I wouldn't encourage it, you might run into css precedence issues (ah browser quirks). better you'd use `merge`, and then pull the id out of that `idFor(merge(orange, black))`

**Comment by treshugart** [comment]
That sounds good.

**Comment by threepointone** [comment]
alright, I'll get to this later today, will ping here when I got something. Thank you so much for the feedback! I'm happy you're trying my lib, and I appreciate your issues :)

**Comment by threepointone** [comment]
just fixed the previous dep issue, will be on this tonight, sorry for the delay!

**Comment by treshugart** [comment]
No need to apologise. Thanks for the update!

**Comment by threepointone** [comment]
Alright then. So I got in 2 helpers named `cssFor` and `attribsFor` for the above, and have pubbed a new version (2.2.2). (`idFor` returns just the id, while you'll need a whole data-attribute, hence `attribsFor`). specifically, the code from my previous example above 'works' (I edited it to reflect the name change). some notes - 
- not heavily tested, and the internal implementation is pretty naive for now 
- haven't documented this in the readme, will do once we nail the api
- attribsFor accepts n rules, and will spit out n attribs; nb: it *doesn't* merge it into one rule.   

a quick output example
```jsx
import { attribsFor, cssFor, style, merge } from './src/index'

let red = style({ color: 'red' })
let blue = style({ color: 'blue' })

let merged = merge(red, blue)

console.log(cssFor(red, blue, merged))
/* 
[data-css-16y7vsu]{ color:red; } 
[data-css-po2wuq]{ color:blue; } 
[data-css-9kt9a5]{ color:blue; } 
*/

console.log(attribsFor(red, blue, merged))
/* 
data-css-16y7vsu="" data-css-po2wuq="" data-css-9kt9a5="`16y7vsu + `po2wuq"
*/
```
let me know feedback, bugs etc, and I'll iterate on this. 
(we could start with a better name for `attribsFor` ugh :P)

**Comment by treshugart** [comment]
Naming is the hardest problem in programming :). I generally abbr attributes as attrs. You could also use `props`, but that'd probably be somewhat more obtuse because they're really attributes.

I'll bump my version and have a play. Thanks again for being so responsive and for all your great work thus far!

I'll leave this open for now, but feel free to close.

**Comment by treshugart** [comment]
I see the changes in your `src` but I think you may have forgotten to run `npm run build` before publishing? All I see in `lib/` and `umd/` is `idFor()` which I'm guessing already existed.

If you just do `npm publish`, is it worth making `npm run build` a `prepublish` script?

**Comment by threepointone** [comment]
pubbed 2.2.3, and will add a prepublish script. sorry and thank you for debugging :( :(

**Comment by threepointone** [comment]
added, fixed.

**Comment by treshugart** [comment]
Epic! I've been using this feature and it's working great, so far.

**Comment by threepointone** [comment]
oh yay, finally :) I'll rename `attribsFor` to `attribs` (or something else) later today and post an update here.

**Comment by treshugart** [comment]
FWIW, I reckon if you're keeping the `For` suffix on the rest of the utilities, then it might make sense to keep it? No strong opinion, though.

**Comment by threepointone** [comment]
I'm open to suggestions for idFor, cssFor as well. But... I must say, the more I type it, the nicer it looks (to me). Might just be desensitized. Will defer taking a decision on this specific bit to later.
