### ISSUE TITLE
Testing that style exists on React component using enzyme

### ISSUE THREAD

**Issue by vamsiampolu** [threepointone/glamor#161]
I would like to test that my components receive the appropriate styling in almost the same way I would test for the existence of a className. Can I use the `label` property in my tests to accomplish that?

I saw the issue on https://github.com/threepointone/glamor/issues/104 and took some of the code from there for use in my mocha test.

The test so far:

```
/* eslint-env node, mocha, es6 */
import React from 'react';
import { styleSheet} from 'glamor';
import { expect } from 'chai';
import { shallow } from 'enzyme';
import Grid from './Grid';

describe('Grid', () => {
  it('is not blank', () => {
    const wrapper = shallow(<Grid />);
    const rules = styleSheet.rules().map(rule => rule.cssText);
    console.log('Glamor Rules:', rules.keys());
    console.log('Props', wrapper.props());
   //check that style has been applied to make it a flex-container
  //without having to test css keys such as flex and so on.
    expect(wrapper).to.not.be.blank();
  });
});
```

My component:

```
import React from 'react';
import { style, merge } from 'glamor';

const container = {
  margin: '0 auto',
  maxWidth: '112rem',
  padding: '0 2rem',
  position: 'relative',
  width: '100%',
  label: 'container',
};

export const containerStyle = style(container);
export const rowStyle = style(row);
console.log(containerStyle);

export default function Grid() {
  return (<div {...containerStyle}>Test</div>);
}
```

I ended up using the following:

```js
describe('Grid', () => {
  it('is not blank', () => {
    const wrapper = shallow(<Grid />);
    const propKeys = Object.keys(wrapper.props());
    const containerStyleKey = Object.keys(containerStyle)[0];
    expect(propKeys.includes(containerStyleKey)).to.equal(true);
    expect(wrapper).to.not.be.blank();
  });
});
```

Here, I have both the `containerStyle` and the `Grid ` component in the same file, is it a good idea to test for the existence of the rule string generated by glamor within the props of the compomemt.

**Comment by findlay-hannam** [comment]
I used sinon to stub css and checked the arguments of each of its calls in the test files. Not ideal as it doesn't check those are actually added to the component.

**Comment by threepointone** [comment]
I'm not certain why you want to test whether specific styles have been added, that's something glamor already tests for. 

Not sure what I actionable thing I can do here, closing this, feel free to reopen if something new comes up.

**Comment by vamsiampolu** [comment]
When using conventional css, we would test that the `className` we wanted was added in the component. Now, we all know that having the `className` does not guarantee that the visual
appearance of the control is correct. However it protects us from elementary mistakes such as oneself or another developer just removing a `className`. 

When using the `better, real and non-redundant css from js solution` such as glamor, If I test that the output of the individual function is correct and that we generate the exact css properties that I want to be applied to my component are returned and I check that the properties have in fact been applied to a component, it would give me a few guarantees that my component will look as expected.

There seems to be an existing solution both in the [styled-components land](https://github.com/styled-components/jest-styled-components) and for [glamor/glamorous](https://github.com/kentcdodds/jest-glamor-react).

The latter only works with `snapshot testing` at the moment and puts the css within the snapshot. The snapshot could fail for any reason and in my opinion cannot be relied upon exclusively for this sort of testing.

Last I checked, `jest-styled-components` provides a `toHaveStyleRule` to match individual rules on a given element but not on any children which means that they have to retrieved via enzyme and then must assert using `toHaveStyleRule`.

Is there any other way of asserting the css/ object applied by a tool such as glamor on a component tree/dom tree without having to either manually go through each element or use snapshots to blanket test them?

**Comment by Rowno** [comment]
I'm running into the same issue. I want to be able to test that logic in my component correctly applies a glamor 'class' under certain conditions. However since the classes are always random it's impossible to test using enzyme, so the only option is to use snapshot testing but that's also pretty much useless due to all the random class names.

**Comment by LySofDev** [comment]
As @vamsiampolu mentioned above, installing `jest-styled-components` and using the `toHaveStyleRule` matcher worked perfectly.
