### ISSUE TITLE
Unitless values

### ISSUE THREAD

**Issue by ccorcos** [threepointone/glamor#167]
Line height can't be set to 1.5 and always defaults to pixels...

```js
const style = css({
  'line-height': '1.5',
})
```

**Comment by ccorcos** [comment]
I suppose '1.5em' works... but it is a quirk still

**Comment by threepointone** [comment]
this is how react does it too, iirc?

**Comment by threepointone** [comment]
um, you should use camelcase, and 1.5 would be preserved. this works -
```jsx
const style = css({
  lineHeight: '1.5',
})
```
