### ISSUE TITLE
Font face example

### ISSUE THREAD

**Issue by ccorcos** [threepointone/glamor#168]
Just requesting an example on how to use font-face to import fonts:

https://github.com/threepointone/glamor/blob/master/docs/howto.md#font-face

**Comment by ccorcos** [comment]
ah, I suppose maybe we'd just use `css.global`?

**Comment by threepointone** [comment]
yes, pretty much, make sure they're the first rules you import! I'm looking to make this better (#40), dunno when I'll get around to it.

**Comment by trigun539** [comment]
Anyway we can do an example of how to use @font-face globally, maybe have multiple font-face example also.
`css.global('@font-face', {
	fontFamily: 'OneDay',
	src: OneDay
});
`
Currently, this works for me. However, not sure how to add other fonts.

**Comment by adamsoffer** [comment]
Has anyone figured out a way to add more than one font to a project using glamor?
