### ISSUE TITLE
Error trying to load babel preset stage-0

### ISSUE THREAD

**Issue by treshugart** [threepointone/glamor#17]
Related to #15, I have to install `babel-preset-stage-0` to get it compiling now.

**Comment by threepointone** [comment]
Clearly I'm a moron who's mucked up something. I'll look.

**Comment by threepointone** [comment]
I'm making a separate sample project to try this out, weird.

**Comment by threepointone** [comment]
holy shit, babel reaches into node_modules and uses its babel config what the hell whyyyy

**Comment by threepointone** [comment]
this might take a bit; I need to wake up right first :| I'll ping back here when I've 'fixed' it

**Comment by threepointone** [comment]
alright, this is now properly fixed. babel/browserify configs now don't leak, and npm pub makes sure to call npm run build via npm prepublish. tested on an sample project, and it 'works'. 

2.2.5!

**Comment by treshugart** [comment]
Thanks, @threepointone!

**Comment by threepointone** [comment]
embarrassing that it happened in the first place :| sorry.
