### ISSUE TITLE
styled-compnents syntax: Warning: Unknown prop  on <div> tag.

### ISSUE THREAD

**Issue by gutenye** [threepointone/glamor#176]
Given

```
styled.div`
  color: ${props => props.primary ? 'red' : 'blue'}
`
```

Got

```
Warning: Unknown prop `primary` on <div> tag.
```

styled-components has [a way to filter non-DOM attributes.](
https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L85)

**Comment by threepointone** [comment]
Yes, I haven't been able to get around to implementing (copying? Lol) all the features yet. Will leave this open till I do

**Comment by threepointone** [comment]
Happy to accept PRs!
