### ISSUE TITLE
create simple react elements

### ISSUE THREAD

**Issue by chrisdrackett** [threepointone/glamor#180]
I see that you are playing with bringing over the styled-component syntax, so this may be moot. That being said, the thing I like about styled-components that I miss in glamor is the quick ability to create a react component that just defines styles and passes all props through. My ideal would be to be able to do this using glamor's normal format (vs. real css).

**Comment by chrisdrackett** [comment]
basically instead of writing:

```
const StyleComponent = (props) => {
  return (
    <div
      {...css({
        backgroundColor: 'red'
      })}
      children={props.children}
    />
  )
}
```

just writing:

```
const StyleComponent = styled.div({
   backgroundColor: 'red'
})
```

or similar.

**Comment by antoinerey** [comment]
Quick draft of a helper function to achieve that. Careful, this may (and probably will) contain many bugs.

```jsx
// import { style } from 'glamor'
// import { propMerge } from 'glamor/react'

const styled = (Type, styles) => ({ children, ...props }) => {
  if (typeof styles === 'function') {
    styles = styles(props)
  }

  styles = propMerge(style(styles), props)

  return (
    <Type { ...styles } { ...props }>
      { children }
    </Type>
  )
}
```

You can use this like so :

```jsx
// Simple div element with a styles object
const Green = styled('div', {
  background: 'blue',
  color: 'white',
})

// Custom component with styles function, to style based on props
const Blue = styled(Green, (props) => ({
  fontSize: props.fontSize || 80,
}))
```

It passes all props through, like styled-compoents does. Hope this can help you 😇

**Comment by chrisdrackett** [comment]
@antoinerey awesome! I actually have been writing something pretty similar, but could not figure out how to get props to work, this gets me a lot closer :)

**Comment by epeli** [comment]
FYI: I've created react-simple on top of glamor which just happens to have the same syntax @antoinerey is proposing. I guess that's quite intuitive API :)

https://github.com/epeli/react-simple

**Comment by donaldpipowitch** [comment]
Awesome! So given that we have [a styled-components-like API](https://github.com/threepointone/glamor/blob/master/docs/styled.md) and [react-simple](https://github.com/epeli/react-simple) I guess we can close this issue.
