### ISSUE TITLE
Redundant property causes react warning "to reuse markup"

### ISSUE THREAD

**Issue by electerious** [threepointone/glamor#182]
I got the following message from React and made several experiments to find what's causing it:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) d="29"><a data-css-17tz759="" href="http
 (server) d="29"><a data-css-13dwcl4="" href="http
```

It turns out that `transition: 'background-color .3s ease, transform .3s ease, box-shadow .3s ease'` inside one component is the problem. I removed it and the warning was gone. But it was not actually the property, it was the reason that the property existed two times. And to make it even harder to debug: Redundant properties don't seem to be a problem in general, but they seem to be a problem in the order I've used them.

Here's the full code of my component. I removed everything not necessary to reproduce the issue:

```js
import React from 'react'
import { css } from 'glamor'

const style = (props) => ({

	self: css({
		transition: 'background .3s ease',
		borderRadius: '100px',
		border: 0,
		boxShadow: '0 10px 20px rgba(0, 0, 0, 0)',
		transition: 'background-color .3s ease, transform .3s ease, box-shadow .3s ease',
	})

})

export default (props) => (
	<a { ...style(props).self }></a>
)
```

What I know:

- Removing everything between the two `transition` properties and the error is gone, too (e.g. `borderRadius`, `border` and `boxShadow`)
- Removing the redundant property fixes the problem
- I'm using Node.js v6.7.0 and glamor v2.20.20
- I rehydrate the ids
- renderStaticOptimized and renderStatic makes no difference
- It's Saturday

**Comment by threepointone** [comment]
I'll have a look, but you seem to have the `transition` key twice in the object? I assume you're trying to do [fallbacks](https://github.com/threepointone/glamor/blob/master/docs/howto.md#fallback-values)?
try this instead - 
```jsx
css({
  transition: ['background .3s ease', 'background-color .3s ease, transform .3s ease, box-shadow .3s ease'],
  borderRadius: '100px',
  border: 0,
  boxShadow: '0 10px 20px rgba(0, 0, 0, 0)'
})
```

**Comment by threepointone** [comment]
[or the other way around, I can't remember in what order css applies fallbacks]

**Comment by electerious** [comment]
My given code produces a different `data-css-` when rendered on the server and client. I assume it shouldn't. The first `transition` key should be ignored without side-effects.

I added the `transition` key twice by accident. The first `transition` is not part of the generated CSS (which is correct), but `data-css-` is different.

What makes the problem complicated: The identifier is only different when the `transition` key appears twice and has the given properties in between.

**Comment by threepointone** [comment]
I'll have a look, thanks for the details!

**Comment by threepointone** [comment]
This is more of a JavaScript problem, and I don't think glamor can really do much here. Closing for now, open to suggestions.
