### ISSUE TITLE
:nth-child doesn't work with css template string function

### ISSUE THREAD

**Issue by jbelfodil** [threepointone/glamor#185]
Hi,

I found an issue there : 

```
const ItemStyle = css`
    & li:nth-child(3n) {
      background:red;
    }
`;
```

This code break the compilation.

For information `:first-child` work fine :)

Thx

**Comment by jbelfodil** [comment]
I can have the expected behavior with : 
```
const ItemStyle = css`
    ${nthChild('3n', {background:'red'})}
`;
```

So I don't know if it's the right way or a real issue..

Thx :)

**Comment by threepointone** [comment]
I'm working on making the css`...` syntax better, closing this simply because of age.
