### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by tuchk4** [threepointone/glamor#186]
Theme example from this doc https://github.com/threepointone/glamor/blob/master/docs/themes.md is not correct because `btnStyle` is never defined. What is the corrrect way to use themes?

```js
//button.js

import { makeTheme } from 'glamor/react'

export const buttonTheme = makeTheme() 

@buttonTheme()
class Button extends React.Component {
  render() {
    return <button {...this.props} {...merge(style({ backgroundColor: 'blue' }), this.props[btnStyle.name])}>
      {this.props.children}
    </button>
  }
}
```

----
 I tried this code
```js
exoprt const buttonTheme = makeTheme();

const Button = (props) => {
  // props[buttonTheme.key] equals to { "data-css-1ezp9xe": ""} 
  return <button>{props.children}</button>
};

export default buttonTheme({
  color: 'green'
})(Button);
```

and Button in case  `<Button>Hello</Button>` props are equal to 

```
{
  "children": "Hello"
  "data-glamor-theme-0": {
     "data-css-1ezp9xe": ""
  }
}
```

I dont  understand how  to use themes.

**Comment by antoinerey** [comment]
Take a look at https://github.com/threepointone/glamor/blob/master/examples/themes.js. I'm not using themes, but the exemple seems to be up to date

**Comment by threepointone** [comment]
Happy to take a PR to fix the docs.

**Comment by threepointone** [comment]
the community seems to be migrating towards https://www.npmjs.com/package/theming 

still open to PRs for docs. closing this issue for now, feel free to reopen if there's anything to share.
