### ISSUE TITLE
css.global or css.insert not defined in typescript type

### ISSUE THREAD

**Issue by chexee** [threepointone/glamor#190]
When I use `css.global()` or `css.insert`, TypeScript throws the following error:

`error TS2339: Property 'insert' does not exist on type '(...rules: Rule[]) => StyleAttribute'.`

**Comment by otbe** [comment]
Good catch! 

Will fix this later today :)

**Comment by threepointone** [comment]
closing this, was live as of 2.20.23. please reopen if there are any issues!
