### ISSUE TITLE
Support Preact

### ISSUE THREAD

**Issue by KyleAMathews** [threepointone/glamor#194]
It'd be nice if you could use the css prop with Preact as well. Been looking at using it with Gatsby.

**Comment by otbe** [comment]
Nice idea! Maybe this should be a standalone npm module?

**Comment by donaldpipowitch** [comment]
We need a lerna repo. In this step we could make glamor/react a standalone module, too 😍

**Comment by threepointone** [comment]
Lerna was part of v3 plans. Feel free to take it up :) wanted to split it
all up, and then make a glamor-legacy package to provide transition plan
from v2.

**Comment by ChristopherBiscardi** [comment]
I have a branch with the lerna transitionary work. Will PR it for visibility later today.

**Comment by threepointone** [comment]
closing this. suggested workaround is to simply make a preact version of https://github.com/threepointone/glamor/blob/master/src/react.js#L13-L25
