### ISSUE TITLE
Hover stops working on resize [chrome]

### ISSUE THREAD

**Issue by techniq** [threepointone/glamor#20]
This could easily be something in my setup, but I created a Codepen [pen](http://codepen.io/techniq/pen/ZOVLZW?editors=0010) to kick the tires of glamor by porting my Aphrodite [example/pen](http://codepen.io/techniq/pen/zBrVxK?editors=0010) and I noticed the following:

Hovering over "This turns red on hover" works until I resize the Codepen preview divider and/or sometimes the entire browser window (or DevTools pane).

It's odd as sometimes I can reproduce it consistently on 1 resize (especially the Codepen preview divider) and sometimes it takes a while (10+ resizes).  Takes a refresh to restore hovering after I cause the issue.

This also seems to occur in the Debug mode of the [pen](http://s.codepen.io/techniq/debug/ZOVLZW), but it took a lot of resizing to reproduce.

**Comment by threepointone** [comment]
I'll take a look later today, thanks!

**Comment by threepointone** [comment]
this is a really weird bug :|

**Comment by techniq** [comment]
So you were able to reproduce it yourself?

**Comment by threepointone** [comment]
yes. it's only on chrome. and I don't even need to resize, just hovering it triggers the bug. and the bug goes away if I use devtools 'toggle element state' to add/remove hover state. soooo weird. I have no code that runs etc. I'm investigating more.

**Comment by threepointone** [comment]
I was able to isolate and reproduce this issue without glamor 

https://codepen.io/threepointone/pen/OXGwRg

I'll submit a bug to codepen and close this issue when I hear from them.

**Comment by threepointone** [comment]
further investigation reveals it's a bug for chrome in general :| this much is enough to trigger it. 

```html
<!DOCTYPE html>
<html>
<head>
  <style type="text/css">
    [data-abc]:hover { background-color: red; }
    @media (max-width: 600px) { 
      [data-xyz] { background-color: red; }
    }
  </style>
</head>
<body>
  <div>
    <div data-abc>one</div>
    <div data-xyz>two</div>
  </div>
</body>
</html>
```

filed chrome bug here - https://bugs.chromium.org/p/chromium/issues/detail?id=639561

**Comment by techniq** [comment]
Nice work on tracking down the root issue. Hopefully the Chrome team resolves it quickly.

**Comment by threepointone** [comment]
good news! I figured out a workaround, published a new version. if you update your codepen to point to 2.6.2, the bug should be resolved. lemme know, and I'll close this issue.

**Comment by techniq** [comment]
I've updated my codepen example to use 2.6.2 with the Chrome workaround and I'm unable to reproduce the bug again.  Thanks.  I'll go ahead and close this issue.
