### ISSUE TITLE
Media query support in `css.global`

### ISSUE THREAD

**Issue by tpreusse** [threepointone/glamor#202]
`css.global` is very convenient and allows to share style objects between scoped and global css.

However if one has a style object with a media query:
```css
const h1Style = {
  fontSize: 42,
  lineHeight: '50px',
  fontWeight: 300,
  '@media only screen and (min-width: 48em)': {
    fontSize: 48,
    lineHeight: '56px'
  }
}
css.global('.RawHtml h1', h1Style)
```
One sees following warning on the console and the media query styles are ignored:
```
Warning: Unsupported style property @media only screen and (min-width: 48em). Did you mean @media only screen and (minWidth: 48em)?
```

Switching to `css.insert` would be an option but seems inconvenient since we'd loose prefixing and the possibility to use the same styles scoped elsewhere:
```js
const h1Rule = css(h1Style)
const H1 = ({children, ...props}) => <h1 {...props} {...h1Rule}>{children}</h1>
```

One alternative could be to export `toCSS` to easily generate css for `css.insert` from a style object.

Currently I use following hack:
```js
import {css, cssFor} from 'glamor'

export const globalWithMediaQueries = (selector, styles) => {
  const plainStyles = {}
  Object.keys(styles).forEach(key => {
    if (key.indexOf('@media') === 0) {
      const mediaStyle = styles[key]
      const className = css(mediaStyle).toString()
      const mediaCss = cssFor(mediaStyle)
      const expectedSelector = `.${className},[data-${className}]{`
      const actualSelector = mediaCss.slice(0, expectedSelector.length)
      if (actualSelector !== expectedSelector) {
        throw new Error(`Expected glamor selector «${expectedSelector}» got «${actualSelector}»\nCSS:\n${mediaCss}`)
      }
      css.insert(
        `${key}{${selector}{` +
        mediaCss.replace(expectedSelector, '') +
        '}}'
      )
    } else {
      plainStyles[key] = styles[key]
    }
  })
  css.global(selector, plainStyles)
}
```
_I'd prefer a clean solution ;)_

Preferred solution would be support for media queries in `css.global` out of the box.

**Comment by epeli** [comment]
I noticed this too. It seems that the styles passed to `css.global` are not transformed using the prefixer?

For example this

```js
css.global(".rw-datetimepicker .rw-input", {
    "::placeholder": {
        color: "orange",
    },
});
```

seem to generate CSS: `.rw-input{::placeholder:[object Object];}` which is obviously not right.

**Comment by epeli** [comment]
Hmmph, I'm using it wrong. I guess the right way to use it would be like this:

```js
css.global(".rw-datetimepicker .rw-input::placeholder", {
  color: "orange",
});
```

but that's not prefixed neither but but the css is generated correctly.  I would prefer the way I used in the previous post because it's consistent with the glamor inline styles.

**Comment by threepointone** [comment]
A better option is to generate a proper rule with css(), and manually add it to the body element. .global and .insert will likely never get prefixing etc. Closing this for now, feeel free to reopen if something new comes up.

**Comment by denis-sokolov** [comment]
It’s confusing since here you say “global will likely never get prefixing”, but 8 months before that it was added in #145, and it is still there.

https://github.com/threepointone/glamor/blob/667b480d31b3721a905021b26e1290ce92ca2879/src/index.js#L516-L522

**Comment by corysimmons** [comment]
I'm basically doing the same thing as @tpreusse and I'm not sure how to manually add a proper rule to the `body` element programmatically without `React.cloneElement` (which seems heavy handed and like it would introduce side effects, vs simply having media query support in `css.global`..).
