### ISSUE TITLE
[server] - `insertRule` rules don't get included in `renderStaticOptimized` output 

### ISSUE THREAD

**Issue by threepointone** [threepointone/glamor#21]
needs a refactor and cleanup ugh

**Comment by shurcooL** [comment]
Hi @threepointone, I'm trying to understand this issue better. Would it cause a JS error such as:

> TypeError: undefined is not an object (evaluating 'this.sheet.insertRule')

Or is that likely unrelated to this?

**Comment by threepointone** [comment]
No that's not related to this. Open a new issue with a sample?

**Comment by threepointone** [comment]
fix live in 2.17.4
