### ISSUE TITLE
Remove `presets` from glamor

### ISSUE THREAD

**Issue by donaldpipowitch** [threepointone/glamor#213]
This is a **breaking change** and part of the `v3` roadmap: https://github.com/threepointone/glamor/issues/83.

# Motivation

Glamor is a CSS-in-JS solution. As there are no predefined Media Queries in CSS and CSS itself isn't opinionated about _how_ your website should look like, Glamor should not make any such assumptions. Predefined Media Queries belong into opinionated layout/design packages and already exist for example in [`glamor-ous`](https://github.com/threepointone/glamor/blob/363d6a6a644bfb9f4efa392c044f79a11c8f6e04/packages/glamor-ous/src/index.js#L19).

# Migration

See TODOs.

# TODOs

- [x] Remove `presets` (https://github.com/threepointone/glamor/pull/212)
- [x] Write a migration guide. (https://github.com/threepointone/glamor/pull/214)

**Comment by ChristopherBiscardi** [comment]
merged #214
