### ISSUE TITLE
Couldn't publish glamor-utils

### ISSUE THREAD

**Issue by donaldpipowitch** [threepointone/glamor#215]
```
ERROR in ./src/index.js
Module not found: Error: Can't resolve 'glamor' in '/Users/philippzins/Workspace/glamor/packages/glamor-utils/src'
 @ ./src/index.js 7:0-46

Attempting to retry publishing glamor-utils...
Error: Command failed: cd /Users/philippzins/Workspace/glamor/packages/glamor-utils && npm publish --tag lerna-temp
```

**Comment by KyleAMathews** [comment]
Perhaps you need to run `lerna bootstrap`? https://github.com/lerna/lerna#bootstrap

**Comment by donaldpipowitch** [comment]
Maybe. Could try it again later. We call `lerna bootstrap` in our `postinstall` hook. It _should_ have worked or I could have not published any other package.

**Comment by ChristopherBiscardi** [comment]
@donaldpipowitch We can probably remove some of the [scripts](https://github.com/threepointone/glamor/blob/81d75fde6854accb732e6a71bdc0d912b7aef83a/packages/glamor-utils/package.json#L14-L22) in any case. I'm not having trouble running prepublish locally so not sure what the issue is.

**Comment by donaldpipowitch** [comment]
Looks like `glamor-utils` _was_ [published](https://www.npmjs.com/package/glamor-utils). No idea what this error was about. I'll close it.

@ChristopherBiscardi Yeah, `scripts` should be cleaned up. I guess we can do that while we introduce TypeScript as we have to update the build config in this step anyway.
