### ISSUE TITLE
[v3] Object, not string, is passed to third-party components when using css prop & patched createElement

### ISSUE THREAD

**Issue by KyleAMathews** [threepointone/glamor#224]
Haven't really dug into this yet but upgraded gatsbygram to v3 and started seeing errors that objects were being passed as the `className` prop not a string. But confusingly the generated glamor classes are still being added to the components.

**Comment by kentcdodds** [comment]
I'm pretty sure that the glamor style objects implement `toString` which allows you to do:

```javascript
const styles = css({})
// styles in an object with {data-css-someId: ''}
<div {...styles} />
```

But you can also do:

```javascript
const styles = css({})
// styles implements toString as: `css-someId`
<div className={styles} />
```

I'm pretty sure that all happens [here](https://github.com/threepointone/glamor/blob/ebf16f8df041f0c4fa955a0319cfb398bed2d814/packages/glamor/src/index.js#L241-L245). Pretty neat right? :)

**Comment by KyleAMathews** [comment]
Glamor has a patched React.createElement you can use which does this automatically with a `css` prop — https://github.com/threepointone/glamor/blob/e8c61d243eba539d721ada1a179f798e77708925/src/react.js#L12

You can write styles like this then

```jsx
<div
  css={{
    color: `red`,
    background: `purple`,
  }}
>
  Hi!
</div>
```

The [Gatsby Glamor plugin](https://www.gatsbyjs.org/docs/packages/gatsby-plugin-glamor/) sets this up for you which I've been really enjoying with the Gatsby v1 sites I'm working. Add the plugin and just start writing styles.

**Comment by kentcdodds** [comment]
I've considered using the plugin, but just don't feel like I want to do that quite yet :)

**Comment by KyleAMathews** [comment]
Embrace your destiny! 😜

**Comment by ChristopherBiscardi** [comment]
@KyleAMathews Did you figure out if this is an issue with glamor or the "third party" components? if glamor can you add a simple reproduction case here?

**Comment by KyleAMathews** [comment]
Eh... it seems to have disappeared. I'll close for now and reopen if I see it again and can figure out how to reproduce it.
