### ISSUE TITLE
grid system

### ISSUE THREAD

**Issue by threepointone** [threepointone/glamor#23]
copy something like http://flexboxgrid.com/ ?

**Comment by vutran** [comment]
How about the new grid layout [spec](https://drafts.csswg.org/css-grid/#overview-grid)?

**Comment by threepointone** [comment]
That looks great! Will read over the weekend, but do you know of any available shims/polyfills? Would make it easy to copy :P

**Comment by souporserious** [comment]
I heard about this library at a conference last year https://github.com/FremyCompany/css-grid-polyfill not sure how well it does though.

**Comment by threepointone** [comment]
there's nothing really to do from glamor's side, and I don't feel like adding another package to core (in the process of emptying them out, really). will assume the answer to this comes from 'userland'. closing for now.
