### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by bluetidepro** [threepointone/glamor#232]
Currently, it looks like there is no changelog with the releases. This is really unhelpful for upgrading. Is there a place to go to easily see breaking changes and general changes with each release?

**Comment by donaldpipowitch** [comment]
We try to document breaking changes [here](https://github.com/threepointone/glamor/blob/v3/docs/migration.md).

We haven't yet discussed how other changes or bug fixes should be documented.

**Comment by ChristopherBiscardi** [comment]
@donaldpipowitch would we be able to use [lerna-changelog](https://github.com/lerna/lerna-changelog) in the future? I'm a bit unfamiliar with the tagging mechanism but it looks like all we would have to do is create a tag for each heading we want and label PRs.

**Comment by threepointone** [comment]
open to PRs, closing this for now, feel free to reopen if there's anything to share.
