### ISSUE TITLE
glamor-styled on npm is missing lib folder

### ISSUE THREAD

**Issue by dignifiedquire** [threepointone/glamor#233]

**Comment by ChristopherBiscardi** [comment]
yeah, this is weird. Not sure how this happened since the lib folder seems to exist when locally building. Thanks for the report. @donaldpipowitch We should watch for this on the next publish.

**Comment by dignifiedquire** [comment]
I also realised that this import https://github.com/threepointone/glamor/blob/v3/packages/glamor-styled/src/index.js#L3 is not working, as `parser` seems to not be something `glamor-raw-css` exports.

**Comment by dignifiedquire** [comment]
The missing `parser` import seems to exist on `master` as well

**Comment by threepointone** [comment]
not sure what path ahead for this, closing for now, feel free to reopen if it's still an issue.
