### ISSUE TITLE
Option to change the class prefix name

### ISSUE THREAD

**Issue by eXon** [threepointone/glamor#239]
Right now, the prefix for the class name is always `css-`. When developing an App that can be embedded into any website, having a customized prefix is highly desirable.

As an example, I would like to prefix all my classes with `projectname-` so I can avoid name collision with my customers CSS.

Is there any way to change the `css-` classname prefix? What would be the impact to add this option?

**Comment by threepointone** [comment]
I'm sorry, but have you seen any actual clashes? Seems unlikely.

**Comment by eXon** [comment]
@threepointone No. Even though there is around 60M possibilities with a 5 characters alpha-numerical hash, it bothers me to have in production something as simple as `css-XXXXX`.

It's also a lot better when debugging to be able to spot quickly your project class from the other classes you don't have control over the Website.

**Comment by eXon** [comment]
@threepointone after testing it on different customers Website, I think the problem is not so much by the `.css-` prefix by the fact that the rule is always at the root. I can't add anything before the rule. 

As an example, a Website might have a `span` rule (I know it's bad practice but I can't control that) and `.css-XXXX` will not have the priority because the element tag has the priority over the class. 

If I could have a prefix on the overall CSS rule, the rule would be `#myApp .css-XXXX` and I would be able to override anything using glamor.

Is that something possible?

**Comment by eXon** [comment]
@threepointone Just found out how to create a plugin that do exactly that. I love how easy it is to code a plugin. Outside your 1 letter variables I love your work ;). Glamor has been a charm to work with.

It's published on NPM: [glamor-prefix-rules](https://www.npmjs.com/package/glamor-prefix-rules) 

Feel free to add it to your list of unofficial plugins

**Comment by threepointone** [comment]
Nice!
