### ISSUE TITLE
Missing d.ts entries for plugins & speedy

### ISSUE THREAD

**Issue by dzearing** [threepointone/glamor#240]
The `plugins` and associated `add` method isn't in the d.ts, need it for supporting custom plugins:

```ts
import { plugins } from 'glamor';
```

I could fix if needed, but sounds like from #229 that the project is planning to move to TypeScript. Need help? (any ETA on the TypeScript conversion?)

We're evaluating using glamor in a number of projects here, having strong reliable type safety is super useful.

**Comment by donaldpipowitch** [comment]
Good to know, thanks. Yeah, we want to move the code base to TypeScript 👍 I hope I find some time soon to start this.

**Comment by dzearing** [comment]
Also same for speedy:

```
import { speedy } from 'glamor';
```

**Comment by donaldpipowitch** [comment]
Regarding TypeScript conversation: https://github.com/threepointone/glamor/issues/242#issuecomment-294260385

**Comment by threepointone** [comment]
I'll accept a PR for the d.ts file. closing this for age, feel free to reopen if you have something to share. thanks!
