### ISSUE TITLE
Discussion: adding an RTL plugin

### ISSUE THREAD

**Issue by dzearing** [threepointone/glamor#241]
In our team we're trying to evaluate the best way to flip rtl rules for developers. We want it to be relatively automatic so that you can't make mistakes. For example, using postcss you can do this using this plugin:

https://github.com/jakob101/postcss-inline-rtl

The problem with the approach we've seen with the generating both ltr/rtl rules using the html[dir=] qualifier in selectors is that it makes the rules really specific, so then we fight specificity when things try to override rules that may have been unnecessarily prefixed.

I think a glamor plugin could provide a really unique opportunity to make RTL work seamlessly, without adding the extra specificity.

It would basically just be a glamor plugin and flip RTL sensitive rules. `left` becomes `right`, etc. This means developers that write non-rtl specific code would get RTLified correctly every time.

We could also allow some convention to define rules that should not be auto-RTLified, like `_left`. There are (very few) scenarios where this would be desidered, but they do exist.

Is there something already like this? Any concerns with this approach? I've prototyped this already and it looks really promising.

**Comment by donaldpipowitch** [comment]
@kentcdodds tweeted something about this topic two days ago: https://twitter.com/kentcdodds/status/851577856425508865.
Maybe this is useful for you?

**Comment by kentcdodds** [comment]
Yeah, just do what I did and magic ensues :) Happy to accept PRs on [rtl-css-js](https://github.com/kentcdodds/rtl-css-js)

**Comment by dzearing** [comment]
Looks good @kentcdodds ! This is exactly what i was looking for. To use with glamor, I'd just do something like:

```js
plugins.add(({selector, styles}) => ({selector, styles: rtlCSSJS(styles) }));
```

**Comment by kentcdodds** [comment]
Bingo! You'd want to wrap that in a check for whether you need to convert RTL based on the user's locale. `rtl-css-js` will not do any check like that for you.

**Comment by dzearing** [comment]
good catch.

**Comment by dzearing** [comment]
working like a champ. I can delete my redundant code now, thanks @kentcdodds :)

**Comment by donaldpipowitch** [comment]
Hooray :tada:
