### ISSUE TITLE
cssnext

### ISSUE THREAD

**Issue by threepointone** [threepointone/glamor#25]
helpers / plugins for http://cssnext.io/

**Comment by threepointone** [comment]
things we should steal - 
[x] custom properties and vars(via native, and js vars)
[ ] `calc()`
[ ] media queries ranges
[ ] `color()`
[ ] hwb, gray, #rrggbbaa
[ ] rgba function (rgb fallback)
[ ] rebeccapurple
[ ] font-variant property
[ ] filter
[ ] initial
[x] rem
[x] :any-link
[ ] :matches 
[x] :not 
[ ] overflow-wrap
[ ] rgb() / hsl() functional notation

things we don't need - 
- custom properties set & `@apply`: because we can simply compose our own rules 
- custom media queries: simple interpolations work fine

**Comment by ChristopherBiscardi** [comment]
Here are some packages for [calc](https://www.npmjs.com/package/glamor-calc-reduction), [color](https://www.npmjs.com/package/glamor-color-function) and [hwb](https://www.npmjs.com/package/glamor-color-hwb).

**Comment by jeroenransijn** [comment]
I am trying to port over a ui library from styled-components. But I rely on using &:matches. Currently this is not working inside of glamor. Is there any roadmap towards this?

**Comment by threepointone** [comment]
landed matches support, putting the rest on backburner
