### ISSUE TITLE
insertGlobal/css.global with empty style object yields 'null' in generated css

### ISSUE THREAD

**Issue by andrewsuzuki** [threepointone/glamor#254]
Example:

```javascript
css.global('a', {})
// => a{null}
```

Also the case for `false` and `''`.

Actual `null` works as it should (no insertion).

**Comment by andrewsuzuki** [comment]
At a quick glance this is probably because `toCSS` doesn't handle the maybe-null value from `createMarkupForStyles`.

**Comment by andrewsuzuki** [comment]
Also occurs for objects with switched values:

```javascript
const backgroundColor = null

css.global('a', {
  backgroundColor,
})
```

**Comment by otbe** [comment]
Confirmed. Will be fixed after first v3 release

**Comment by threepointone** [comment]
should go live in next patch release, likely by the weekend.

**Comment by threepointone** [comment]
live in 2.20.29
