### ISSUE TITLE
suggesstion: optimise hashing

### ISSUE THREAD

**Issue by amir-arad** [threepointone/glamor#259]
I'd love to optimise the hashing function to stop using `JSON.stringify`,

and solve the isomorphic duplication issue (where `{foo:1, bar:1}` gets different hash than `{bar:1, foo:1}`).

Would be easier for me if there's a pointer for performance tests of this process

**Comment by otbe** [comment]
Nice idea. As of now there are no performance tests for ```hashify```, but there are tests. 
There is WIP [branch](https://github.com/mosbahh/glamor/tree/v3-typescript) for our typescript transition in v3 where the hash algo and ```hashify``` were separated. Maybe you can use this as a starting point and implement some benchmarks and your proposed changes?

**Comment by threepointone** [comment]
closing this, feel free to reopen if you have anything to share.
