### ISSUE TITLE
linting

### ISSUE THREAD

**Issue by threepointone** [threepointone/glamor#26]
dev only linting would be nice

**Comment by vutran** [comment]
I can help set this up with `eslint` and maybe with [airbnb](https://github.com/airbnb/javascript/)'s guide unless you have another preference?

**Comment by threepointone** [comment]
Yes, this issue deals with linting the css being input, not glamor itself. I figure it'll be a plugin that only gets added in dev mode.

**Comment by rafaelrinaldi** [comment]
@threepointone Anything specific in mind for this feature? I can give it a shot with stylelint.

**Comment by threepointone** [comment]
Nothing specific, open to ideas. 

An intermediate solution - I checked, and https://github.com/styled-components/stylelint-processor-styled-components 'just works' on the tagged literal syntax feature that I'm working on.

**Comment by threepointone** [comment]
putting this on backburner
