### ISSUE TITLE
,kkkkkkkkgo;m \-jh

### ISSUE THREAD

**Issue by Vorozhtsoff** [threepointone/glamor#267]

**Comment by threepointone** [comment]
Right on, right on.

**Comment by donaldpipowitch** [comment]
Do you have a code example for this? Which version did you use?

**Comment by donaldpipowitch** [comment]
:) Everything's is good. If you have any questions feel free to ask :) Thank you for looking into glamor ❤

**Comment by Vorozhtsoff** [comment]
Sorry,  this issues opened by my cat, It likes to lay on my opened laptop.
