### ISSUE TITLE
Glamor-generated CSS into a static css file?

### ISSUE THREAD

**Issue by berbaquero** [threepointone/glamor#270]
Sorry if this has been asked before — couldn't find it if so.

Is it possible to take all the CSS that glamor generates and put it into an actual CSS file, to be served statically?

If I understand correctly, even if I generate the CSS via server-side rendering, it will just be a `<style>` tag in the document. Or am I wrong in that assumption?

My main concern is that I would like to be able to generate and serve a "traditional", static CSS file, that is cacheable and simply "reusable" across page views, instead of regenerated on the server and included on every page response as an inlined `<style>` tag.

Is there a way to accomplish this?

**Comment by threepointone** [comment]
Totally doable! You have to do the same steps indicated in docs/server.md for the pages required, and follow up by writing the `css` content to a .css file. Do try to `rehydrate` the `ids` as indicated too, to prevent double addition of rules (not a *very* big deal if you can't, but is ideal)

There are some optimizations we could do here, to extract common css from files to eg `common.css` file etc, but we haven't gotten around to simplifying it yet.

**Comment by berbaquero** [comment]
Awesome! Thanks for super quick response and the guiding!

I'll give this a shot :) 👍
