### ISSUE TITLE
Problem with glamor/babel

### ISSUE THREAD

**Issue by vinicius-sabadim** [threepointone/glamor#272]
Before all, thanks for this amazing project!

I'm facing some problems trying the lint option.
I copied the example

```
let rule = css`
  color: red;
  font-family: helvetica, sans-serif;
  :hover {
    color: blue
  }
  @media(min-width: 300px) {
    color: green
  }
`
```

and my .babelrc is

```
{
  "presets": [
    "env",
    "react"
  ],
  "plugins": [
    "transform-class-properties",
    "transform-object-rest-spread",
    "transform-regenerator",
    "glamor/babel"
  ]
}

```

but when I try to run my application, I see the error
<img width="434" alt="screen shot 2017-06-15 at 15 33 57" src="https://user-images.githubusercontent.com/7515783/27196252-1832e578-51e0-11e7-8a89-925c18252632.png">

What am I doing wrong?

**Comment by threepointone** [comment]
could you try putting glamor/babel *before* the others?

**Comment by threepointone** [comment]
closing this, please reopen if you have a reproducible test case you can share.
