### ISSUE TITLE
Autoprefixer doesn't handle selectors

### ISSUE THREAD

**Issue by pluma** [threepointone/glamor#273]
Most browsers don't support the standard `:fullscreen` pseudoclass yet, so I thought the prefixer would automatically generate the relevant variants (like `-webkit-full-screen`) but it turns out that it only handles properties, not selectors.

As far as I can tell, implementing this would require duplicating the styles because browsers ignore selectors if they contain any unknown parts (like the vendor prefixed pseudoclasses for other browsers) even when there's more than one of them.

Are there any plans to support selector prefixing?

**Comment by threepointone** [comment]
we already do this manually for :placeholder, I would consider one for :fullscreen too. as a workaround, you could do this manually for now?

**Comment by threepointone** [comment]
Do you have a handy list of selectors that need to be prefixed?

**Comment by pluma** [comment]
`:fullscreen` and its variants were the only ones I've run into. It's possible to work around but it's a bit ugly because the styles need to be duplicated for each variant. Thanks for looking into this.

**Comment by threepointone** [comment]
this should work in 2.20.27. feel free to reopen if it doesn't.

**Comment by pluma** [comment]
Awesome, thanks!
