### ISSUE TITLE
bundle size increase 

### ISSUE THREAD

**Issue by threepointone** [threepointone/glamor#282]
3.0.0-2 seems to have increased in size, to 13 kb gzipped (!) any idea, @donaldpipowitch, @otbe?

**Comment by donaldpipowitch** [comment]
@otbe will look into that. Maybe a little bit of runtime overhead from webpack and/or TypeScript which can be optimized. We also use `inline-style-prefixer` now directly (which solves some bugs AFAIK), which is probably bigger as the previous copied solution. Maybe we can cut some bytes with prepack, too :)

**Comment by threepointone** [comment]
I tried prepack, it breaks because I can't figure out a good solution for our dom calls. Will bug folks at work for any leads.

**Comment by threepointone** [comment]
imo it would be a better call to go back to the previous autoprefixer, since other prefixers can be added by the plugin system.

**Comment by donaldpipowitch** [comment]
Two notes:

1) Maybe we should remove the autoprefixer from `glamor` itself completely? And clean up `glamor-autoprefixer` instead, so people can choose to use it or not.

2) [`react-css-property-operations`](https://github.com/smyte/react-css-property-operations) (imported [here](https://github.com/threepointone/glamor/blob/fe0b233372de6881455d90b4a31fd91fa1682f42/packages/glamor/src/css/index.ts#L3)) is published as a webpack build and it looks like webpack doesn't process other webpack builds. That means that `process.env.NODE_ENV !== 'production'` can't be optimised in production builds. I'd recommend to remove `react-css-property-operations` as a dependency and use `react-dom` directly. `react-css-property-operations` basically [does the same thing and nothing more](https://github.com/smyte/react-css-property-operations/blob/master/src/CSSPropertyOperations.js#L1). But now we can set `process.env.NODE_ENV` correctly.

**Comment by threepointone** [comment]
1. I don't agree, the autoprefixer is a key component, and shouldn't expect peeps to install it everytime, and I don't think it belongs in another package. The bugs iirc were to do wit ie10 compat for flexbox; I'd rather lose ie10 compat altogether. 
2. We had vendored CSSPropertyOperations into our codebase, I'd like to see that come back, no reason to use an external package. Don't use react-dom directly, there's no guarantee that this package is used only with react libs.

**Comment by donaldpipowitch** [comment]
Pull requests welcome 😄

**Comment by threepointone** [comment]
Noted. Will do it myself.

**Comment by threepointone** [comment]
closing this, will revisit when v3 plans are concrete.
