### ISSUE TITLE
BrowserStack issues?

### ISSUE THREAD

**Issue by donaldpipowitch** [threepointone/glamor#284]
Hi @threepointone,

the CI is currently broken and we don't know why. It looks like the project can be build correctly and then just aborts. @otbe downloaded the corresponding Travis image and run the test suite with our own BrowserStack credentials and everything seemed to work fine (besides another inconsistency of css text output in IE). Any idea what's wrong? Can you look into our BrowserStack account, if you can see any error logs or something like that?

Thank you!

**Comment by threepointone** [comment]
I'm thinking of moving to saucelabs, in general my experience with browserstack hasn't been great. Any objections?

**Comment by donaldpipowitch** [comment]
No. Only used SauceLabs for OSS before :)

**Comment by threepointone** [comment]
I've whacked out phantomjs, looks like it was causing problems. I'll close this for now, browserstack seems to be working fine again. will revisit the saucelabs decision later,
