### ISSUE TITLE
impement atomic class

### ISSUE THREAD

**Issue by liadbiz** [threepointone/glamor#285]
Hey guys,
I am creating a component library with react and glamorous which build opon on glamor, but when I render buttons with diffrent colors, all this buttons have diffrent classnames with almost same styles except border-color, I am wondering if I can give this buttons a classname for shared styles and another classname for border-color, which wil save some bytes.

I saw [styletron](https://github.com/rtsao/styletron) support this out of box, but I dont want to change glamorous to styletron. And, I think it's a good feature! what do you @threepointone  and other guys think?

**Comment by threepointone** [comment]
Ive considered this, but it expands the scope of this project too much, and I'm not a fan of the debugging experience. We might revisit this in the future, but closing for now.
