### ISSUE TITLE
Coordinate v3 release with glamorous@4, jest-glamor-react@2, and release of https://glamorous.rocks?

### ISSUE THREAD

**Issue by kentcdodds** [threepointone/glamor#286]
HYPE!

Just wondering how close v3 is and whether ya'll would be interested in coordinating releases. I'm hoping that the website will be ready within a week or two. There are a few breaking changes I want to make to glamorous and jest-glamor-react as well. This will be accompanied by a blog post announcing the changes and release of [the website](https://rc.glamorous.rocks/).

What do you think?

**Comment by threepointone** [comment]
I'm rethinking some of v3's plans, and am considering on bringing back some stuff that's been put into other packages. As such, might be longer than a week?

**Comment by kentcdodds** [comment]
Sounds exciting. Ours might also be longer than a week. Take your time and ping me here. I'm sure that we could find people willing to contribute to help push v3 along :smile:

**Comment by donaldpipowitch** [comment]
Hi, I'd probably like to step a little bit back. I'm quite busy with work, other projects and holidays for the unforeseeable future 😿 I'm really sorry.

Nice to see @threepointone back on board again 👍

**Comment by threepointone** [comment]
reaching out to kent out-of-band to resolve this
