### ISSUE TITLE
No exported member

### ISSUE THREAD

**Issue by leoalves** [threepointone/glamor#288]
I was importing select, merge and style from glamor, but after upgrade to 3.0.0-2 it seems they don't exist anymore.
`import { select, merge, style } from 'glamor'`

I tried assiginig css to those properties but it doesn't work.

```
import { css } from 'glamor'
const select = css
select(' a, a:hover, a:active', {
      color: config.linkHoverColor,
      textDecoration: config.linkHoverDecoration
    }),    
```
doesnt work anymore. The params are different. Is it possible to make it work with the new version or I need to replace everywhere I use select with css ?
Thanks

**Comment by donaldpipowitch** [comment]
These exports were removed, because we slimmed down the API: https://github.com/threepointone/glamor/issues/229.

`merge` and `style` are just aliases to `css.` `select` can also be replaced with `css`:

```js
select(selector, style) → css({ [selector]: style })
```

Feel free to close the issue, if this answers you questions :)

**Comment by leoalves** [comment]
Cool. Will change my code. 
Thanks
