### ISSUE TITLE
SSR Broken?

### ISSUE THREAD

**Issue by VincentBailly** [threepointone/glamor#291]
The document for SSR recommends to import renderStatic this way:

import { renderStatic } from 'glamor/server'

However it does not seem that the module glamor/server exists. Am I missing something?

**Comment by threepointone** [comment]
Are you trying v3 by any chance?

**Comment by blamarvt** [comment]
It looks like `renderStatic` was moved to `glamor-server`. This tripped me up earlier, I just had to 

    npm install glamor-server

**Comment by threepointone** [comment]
This shouldn't be an issue if you're using v2. Are you on v3 by any chance?

**Comment by threepointone** [comment]
it appears v3 was marked as latest, I've marked v2 again

**Comment by threepointone** [comment]
please reinstall glamor, and use glamor/server as normal

**Comment by VincentBailly** [comment]
The problem was that I had the v3 version because of installing latest. Thank you for the fix.
