### ISSUE TITLE
v3(?) plans

### ISSUE THREAD

**Issue by threepointone** [threepointone/glamor#296]
Based on my conversations with a number of consumers, and trying stuff out myself, I now believe that I bit off more than was necessary with the previous v3 plans. the proposed splits would have just made stuff harder to get started, and the rewrite to typescript would have reduced iteration speed and made the codebase less familiar to newcomers (and myself!). Further, it was too big a change without being informed by usecases, and would have weakened the ecosystem. And even further, other stuff has happened in the css-in-js world, and we would have been in a weaker place to accommodate it.  

I want to be clear, I am immensely grateful to the work from @ChristopherBiscardi, @otbe, and @donaldpipowitch, and I take full responsibility for leading them down the path they went. They've been phenomenal, and I'm utterly indebted to them for holding ship for the past few months. glamor would have likely died without them. 

So I'm pulling back on the large scale plans, and instead, glamor will now favour incremental improvements over large scale ones, and be usecase-driven in adopting/creating new features. 

In the short term, I want to clear the backlog of issues (already wiped out 50 over the last couple of days). I want to tackle #238, #201, and possibly tackle issues around the literal syntax(#188, #187, #140, etc), and maybe some others.

Long term plans - 

1. documentation - the documentation story around glamor is weak, where peeps aren't even sure of what it can and can't do. The composition model is pretty superior and unique, and I'd like to surface that up to consumers. Recipes and patterns, performance tips... all that. I've gotten by with just markdown files so far, but I guess it's time to grow up and make a real website. I'd also like to make sure that peeps will be able to contribute to the website/codebase easily.

2. ecosystem - glamor has a healthy ecosystem of direct consumers and libraries, and I'd like to service them better. Glamorous, gatsby come to mind, but there are more. Further, there's an opportunity to service libraries like emotion with a subset of glamor's features/code. 

3. perf/benchmark formalisation - it's all very well and good to make claims on twitter based on benchmarks that I've run privately, but I'd like to formalise that entire effort, across a variety of vectors. Further, I'd like to measure it across releases to make sure I don't regress. To be clear, This isn't to compare with other libraries, but to make sure glamor is fast enough for my purposes.

4. features - Nothing too drastic; I'd like to figure out support for iframes, web components, leverage babel-macros for the literal syntax, flow typings, help the reasonml folks with first class support, formalise/absorb glamor-inline, prep for streaming html/react v16. I might also deprecate stuff like glamor/ous (the skeleton port) considering no one really uses it. Further, I'd like to explore codemods for when I do inevitably break the api. (To be clear, I'd *like* these, but no guarantees about any)

5. bundle size - work on reducing the bundle size will always continue. figuring out a good plan that can leverage webpack's scope hoisting, dead code elimination, etc, besides lightening up our dependencies a bit.

None of this is 'final'/set in stone, and will depend on how much time I can spend on it, juggling a real life and new job in a strange country, all that. While I'm open to feedback, please understand that I'll be selfish and consider my own health and sanity above all else.

**Comment by threepointone** [comment]
cc @kentcdodds @KyleAMathews @thk44

**Comment by nicholaswyoung** [comment]
As a user of Glamor, this is fantastic news. 👍

**Comment by threepointone** [comment]
have made issues for some of the new features., closing this.
