### ISSUE TITLE
Order of prefixed properties have changed

### ISSUE THREAD

**Issue by planttheidea** [threepointone/glamor#298]
This is an example, but when using `flex-grow` on items in `2.20.30`, prefixed properties came before the spec properties, so the spec always won if supported:

![image](https://user-images.githubusercontent.com/9438233/28499969-06764ef2-6f8f-11e7-8d6a-ccf8eac86628.png)

However upgrading to `2.20.32` the order of these properties have changed, placing the prefixed properties last and therefore winning over the spec properties:

![image](https://user-images.githubusercontent.com/9438233/28499985-48eb041c-6f8f-11e7-819c-ed2241d7f145.png)

I also noticed that the number of prefixed properties have been reduced, and I assume that is from [this commit](https://github.com/threepointone/glamor/commit/e9643f558db5e74b037fc13ab4507db9daa63b8e) (which is an awesome thing, btw), but I worry that the prefixed (legacy) property winning can cause weird regression issues.

I'm hoping the fix may be as simple as a basic sort (where anything with a leading `-` comes first) before being added to the `style` tag?

**Comment by threepointone** [comment]
That's odd, I'll investigate.

**Comment by planttheidea** [comment]
I've traced it to the serialization that occurs in `src/CSSPropertyOperations/createMarkupForStyles` ... I'm gonna try to work a fix so that I can submit a PR instead of just complain haha

**Comment by threepointone** [comment]
that should be fine though? I've made an issue in the prefixer package as well https://github.com/rofrischmann/inline-style-prefixer/issues/133

**Comment by threepointone** [comment]
hmm, it's iterating the keys in a different order than expected

**Comment by planttheidea** [comment]
I have a fix locally, passes all the tests ... will be creating a PR in a few if its alright.

**Comment by threepointone** [comment]
sure, go for it. you can share the snippet here too, I'm hacking on it myself rn

**Comment by planttheidea** [comment]
```javascript
export function createMarkupForStyles(styles, component) {
  const serialized = Object.keys(styles)
    .sort((a, b) => {
      return (b.indexOf('--') === 0) ? b : processStyleName(b)[0] === '-' ? 1 : 0;
    })
    .reduce((styleString, styleName) => {
      const isCustomProp = (styleName.indexOf('--') === 0)
      const styleValue = styles[styleName]

      if (process.env.NODE_ENV !== 'production' && !isCustomProp) {
        warnValidStyle(styleName, styleValue, component)
      }

      if (styleValue == null) {
        return styleString;
      }

      return isCustomProp ? `${styleString}${styleName}:${styleValue};` :
        `${styleString}${processStyleName(styleName)}:${dangerousStyleValue(styleName, styleValue, component)};`
    }, '')

  return serialized || null
}
```

Basically converted it to be more function with use of `Object.keys` which allowed for sorting prior to serialization. I couldn't think of a way to order the keys without iterating over them prior to reduction, and this seemed the most efficient way to double-iterate.

**Comment by threepointone** [comment]
not sure this is the best way to do it, might lead to weird behaviour when I'd need it in another order.

It looks like the object is created correctly, but it's pulling the keys in the wrong order. I'll investigate further for a better solution, and/or wait for i-s-p to come up with a solution.

**Comment by threepointone** [comment]
weirdness 
<img width="728" alt="screen shot 2017-07-23 at 15 01 31" src="https://user-images.githubusercontent.com/18808/28500436-dab0fd52-6fb7-11e7-8f20-ade225b85c92.png">

**Comment by planttheidea** [comment]
yup ... does not surface with `display: flex;`, only with `flex-grow` or shrink or whatever ... super weird

**Comment by threepointone** [comment]
it's because isp uses the array/fallback method for display, but separate keys for the others, and if you look at the screenshot, the order is fine in the collapsed form, but reorders in the expanded form/ when keys are enumerated.

**Comment by planttheidea** [comment]
yupyup I got ya ... from what I can tell, it looks like alphabetic ordering is used, and capitalization matters in the expanded display, but not in the collapsed (and also not in iteration).

**Comment by threepointone** [comment]
also just noticed that the prefixer mutates the input style, ack ><

**Comment by planttheidea** [comment]
How about something like this?

```javascript
export function createMarkupForStyles(styles, component) {
  let serialized = '';

  for (let styleName in styles) {
    if (!styles.hasOwnProperty(styleName)) {
      continue;
    }

    const isCustomProp = (styleName.indexOf('--') === 0)
    const styleValue = styles[styleName]

    if (process.env.NODE_ENV !== 'production' && !isCustomProp) {
      warnValidStyle(styleName, styleValue, component)
    }

    if (styleValue == null) {
      continue;
    }

    if (isCustomProp) {
      serialized += `${styleName}:${styleValue};`
    } else {
      const processedName = processStyleName(styleName);

      serialized = processedName[0] === '-' ?
        `${processStyleName(styleName)}:${dangerousStyleValue(styleName, styleValue, component)};${serialized}` :
        `${serialized}${processStyleName(styleName)}:${dangerousStyleValue(styleName, styleValue, component)};`
    }
  }

  return serialized || null
}
```

No additional iterations, a better guarantee that the property is indeed prefixed before ordering the string, and you get to keep the original coding style of for-in (looks like `Object.keys` + `reduce` was less performant).

**Comment by threepointone** [comment]
I'll consider it. I'm also looking at writing my own, non-mutating version of isp's createPrefixer.js (don't need it's nesting/array support anyway)

**Comment by planttheidea** [comment]
Fair enough, I'll just set up the PR with this and let it's fate rest in your hands. Anything I can do, lemme know.

**Comment by threepointone** [comment]
do you have an example of a prefixed property having the different/wrong value than a non prefixed property? the author of the prefixer doesn't seem to think this is a problem per se.

**Comment by planttheidea** [comment]
Its not a problem with the values being incorrect, the values always line up ... the issue is that when you convert the objects into strings for insertion into the `<style>` tag it places the prefixed properties *after* the spec properties. This can cause unexpected behavior, and really is counter-intuitive (as with all fallback mechanisms, the spec always comes last because it should win out).

In the screenshots I provided that started this whole thing, `flex-grow` comes after `-webkit-flex-grow` in version `2.20.30` (which is correct behavior, based on the above logic), however `-webkit-flex-grow` comes after `flex-grow` in version `2.20.32`, which means that the prefixed property "wins" over the spec property. This is why I provided the PR ... it simply places prefixed properties before non-prefixed properties when being serialized into a string, ensuring that correct order is maintained for CSS overrides.

**Comment by planttheidea** [comment]
I can confirm that the behavior of the prefixed properties is not the same as those for the spec properties, as I have witnessed visual bugs related to use of the prefixed properties. An example is creating an element that is both the child of a `column` flex container and is a `column` flex container itself where the height is not a specific pixel value. In all current browsers, the spec will let the element grow to fix its own container and then base its calculated height for its children on that growth. With the prefixed properties, the calculated height is determined to be `0`, and simply unchecking the prefixed values in devtools to let the spec values take precedent fixes it.

It appears the assumption that the prefixed properties are no longer being maintained when the spec properties are available is indeed true. So just a heads up, labeling this as a "question" seems less appropriate than "bug".
