### ISSUE TITLE
prevent `label` from being added to the css applied

### ISSUE THREAD

**Issue by kentcdodds** [threepointone/glamor#303]
Because [this](https://codesandbox.io/s/BgWYBEZMx) doesn't seem right and I think people will be concerned about it and not use the `label` feature.

<img width="1415" alt="screen shot 2017-07-24 at 5 46 48 pm" src="https://user-images.githubusercontent.com/1500684/28550762-362be12a-7098-11e7-88e5-6022d3d26760.png">

Also, side question, what would happen if I nested the label? Nothing?

**Comment by threepointone** [comment]
I could totally remove the label from the actual css being injected, not a problem.

Nested labels should get combined; idea being to show labels of all the styles being composed. In a previous version, it would sorta approximate the tree of labels and show it in the data attribute value itself, dialled it back to simple concatenation. I'm happy to iterate on this based on feedback, let me know what works best.

**Comment by kentcdodds** [comment]
Concatenating makes sense :+1:

**Comment by kentcdodds** [comment]
Also: `css({label: 'foo'})`...

I would expect that to be: `css-foo-nil`

but it's `"css-foo-1cepw5k"`

**Comment by threepointone** [comment]
I thought about it, and I think it labels should participate in hashing, if only to differentiate origins. I'm going to leave that behaviour as is for now, but let me know if it causes actual problems. 

(there's also the fact that it would be expensive to remove the labels before hashing, but we'll cross that bridge if and when we come to it)

published 2.20.37, that doesn't include the label in the generated css 🎊

**Comment by kentcdodds** [comment]
Perfect! Thanks!
