### ISSUE TITLE
content issue

### ISSUE THREAD

**Issue by kentcdodds** [threepointone/glamor#304]
There seems to be a regression somewhere.

Code:

```javascript
const className = css({
  '&::before': {
    content: 'initial',
  },
})
```

[Before](https://codesandbox.io/s/o2B21prWA):

<img width="58" alt="screen shot 2017-07-25 at 12 16 50 am" src="https://user-images.githubusercontent.com/1500684/28560203-94f86cc4-70ce-11e7-9720-db203706a677.png">

[After](https://codesandbox.io/s/q1DrD9WR): 

<img width="97" alt="screen shot 2017-07-25 at 12 16 54 am" src="https://user-images.githubusercontent.com/1500684/28560217-9c12d40e-70ce-11e7-8fa1-ac9b72792ac2.png">

**Comment by threepointone** [comment]
fix live in 2.20.36
