### ISSUE TITLE
Too many css styles

### ISSUE THREAD

**Issue by blackswanny** [threepointone/glamor#324]
In our project we found that glamor generated too many css style rules. Most of these rules are not used by markup on the page, they are present only in inlined glamor styles data.
Our version is 2.20.26 (supposed to be, how to check via browser?). It's a server-side rendering
Any suggestions of why it may happen? Is there any config, that may cause it?

**Comment by threepointone** [comment]
can you go into more detail? repro and/or screenshots would help.

**Comment by threepointone** [comment]
do you use `renderStatic`? could you try replacing with `renderStaticOptimized` instead?

**Comment by blackswanny** [comment]
yes. it helped.
