### ISSUE TITLE
env-specific vendor prefixes

### ISSUE THREAD

**Issue by threepointone** [threepointone/glamor#35]
on server side, it should do the current behavior, which is adding all prefixes 
on browser, only needed prefixes

**Comment by threepointone** [comment]
live in 2.17.5

**Comment by ismay** [comment]
Just out of curiosity, when you say:

> which is adding all prefixes 

What exactly does 'all prefixes' mean here? There must be a certain cutoff point for browsers that you don't support right (like ie < 9 or something)? Just wondering how that's defined.

**Comment by threepointone** [comment]
my autoprefixer is a vendored version of https://www.npmjs.com/package/auto-prefixer, so whatever that supports. I'm aiming for IE 10 and above tho.

**Comment by ismay** [comment]
Ah ok. Would be great if this were configurable, for projects that want to support more than that.  Thanks for the quick reply btw 👍

**Comment by threepointone** [comment]
It is indeed configurable! The documentation is lacking on this, but basically autoprefixes are added via the plugin system. You can clear out the plugins and add your own. This should get simpler / better docs in v3. https://github.com/threepointone/glamor/blob/master/docs/plugins.md

**Comment by ismay** [comment]
Ah I didn't realise that! Ok great, thanks! Congratulations on this awesome lib btw. 👍
