### ISSUE TITLE
how to use -webkit-line-clamp

### ISSUE THREAD

**Issue by FengShangWuQi** [threepointone/glamor#388]
![image](https://user-images.githubusercontent.com/17982705/47829834-5be71700-ddc4-11e8-8d2a-5e9f090a9939.png)

![image](https://user-images.githubusercontent.com/17982705/47829788-23473d80-ddc4-11e8-99a3-5d4f7a584a9b.png)

**Comment by khamiltonuk** [comment]
@FengShangWuQi Why did you close this, has it been resolved? I am currently facing the same issue. 😄 
For now I will put the styles directly on the `<div />` element using the style prop
