### ISSUE TITLE
How to use css prop?

### ISSUE THREAD

**Issue by KyleAMathews** [threepointone/glamor#43]
https://github.com/threepointone/glamor/blob/master/docs/createElement.md

E.g. how do I use this for `media`, `hover`, etc.? It seems like a nice simplification for React but the docs aren't clear about how to use this special prop.

**Comment by KyleAMathews** [comment]
Oh this is just for `style` then? https://github.com/threepointone/glamor/blob/efc5dc4e7d416e3c7deba30f515704d953cdda92/src/react.js#L15

**Comment by threepointone** [comment]
no, you can pass any rule into it 
```jsx
<div css={media(...)}></div>
```
it also accepts arrays, and wraps 'plain' objects with `style`, so this works too 

```jsx
<div css={[{color: 'red'}, hover({ color: 'blue'}), media(...)]}></div>
```

happy to make enhancements if I can make this easier/ simpler.

**Comment by vdanchenkov** [comment]
Are there any significant performance issues with invoking style() on every render?

**Comment by threepointone** [comment]
Not really, it barely registers in the perf profile. On my laptop, I can do about 10000 unique styles in under 50ms (in prod mode). As a comparison, *all* of twitter's css is under 10k styles iirc. And when rerendering, it barely even shows in the perf profile. 

Please let me know if do you see any issues, because I keep testing this to be certain.

**Comment by threepointone** [comment]
For posterity's sake; 2 things you can do if it bothers you much - 

- declare the styles *outside* `render`, and spread the object when rendering
- prerender styles with `renderToStatic` and feed `ids` into `hydrate` while starting up

however, I personally haven't found the need to use these *yet*.

**Comment by threepointone** [comment]
closing this, please reopen if I've missed something.
