### ISSUE TITLE
Warn about usage for animation

### ISSUE THREAD

**Issue by vdanchenkov** [threepointone/glamor#45]
I just tried to use it for animation and ended up with a pile of silly css rules 😹

``` jsx
<div {...style({ width: x })}/>
```

I guess we need to show a dev warning for this case. I can address it later when I got better feel of the library.

**Comment by threepointone** [comment]
Yeah, need to add a warning to the docs, but without scaring users :P

I'm considering a warning at 5k styles in dev mode, would that be a good start? 

(I even had some earlier work that wold have made this possible, but it's way too fiddly.)

**Comment by AndrewIngram** [comment]
How about a babel plugin that detects usage of render-time variables and uses real inline styles for those and only passes static stuff to glamor?

**Comment by threepointone** [comment]
Render time variables are fine, that's how you'd do vars and themes etc. 

Tangentially - What I'd *like* is a dev tools panel, that tracks how many rules have been added, timelines, stats, etc :)

**Comment by threepointone** [comment]
closing this because it's vague in scope, lemme know if you have any new leads.
