### ISSUE TITLE
Specificity confusion in Glamor with multiple inlined style/media

### ISSUE THREAD

**Issue by KyleAMathews** [threepointone/glamor#54]
I have a div that I'm adding some styles too:

```javascript
        <div
          {...style({
            paddingTop: rhythm(1),
            textAlign: 'center',
            maxWidth: 960,
            margin: '0 auto',
          })}
          {...media(presets.tablet, {
            paddingTop: rhythm(3),
          })}
        >
```

The media `paddingTop` should always win but when it's at `rhythm(3)` (Typography.js helper function) it doesn't but if I change it to `rhythm(3.5)` it does.

Screenshots from chrome devtools:

*rhythm(3.0)*
<img width="344" alt="screen shot 2016-09-16 at 2 55 47 pm" src="https://cloud.githubusercontent.com/assets/71047/18602415/cc0b806c-7c1d-11e6-9f34-22b66b426512.png">

*rhythm(3.5)*
<img width="348" alt="screen shot 2016-09-16 at 2 56 14 pm" src="https://cloud.githubusercontent.com/assets/71047/18602416/cc107018-7c1d-11e6-88c1-3bbad3c38868.png">

It looks like it's just the hash length for the media query attribute that's changing?

**Comment by KyleAMathews** [comment]
Hmm... I didn't know media queries don't affect specificity http://stackoverflow.com/questions/19038240/media-query-styles-not-overriding-original-styles

So I guess it really is just the length of the data attribute name changing?

**Comment by KyleAMathews** [comment]
Oh and I get now why I hadn't realized before media queries don't affect specificity — it's because I always put the larger queries after the smaller ones (or the default) so overriding just happened.

Can we enforce that in Glamor? That later `style` or `media` props override earlier ones?

**Comment by KyleAMathews** [comment]
Ahhh.... https://github.com/threepointone/glamor/blob/master/docs/howto.md#multiple-styles-to-an-element

**Comment by threepointone** [comment]
did using merge/compose work? 
[really wish css was applied in the order of declaration on the element, not the order in the stylesheet. tch.]

**Comment by KyleAMathews** [comment]
Yes it did! Got side tracked and didn't follow up. Shouldn't be have doubted that you hadn't already thought of everything ;-)
