### ISSUE TITLE
Plugin execution order is reversed

### ISSUE THREAD

**Issue by vdanchenkov** [threepointone/glamor#55]
Last plugin run first. Is it intentional?

**Comment by threepointone** [comment]
yes, otherwise it wouldn't be possible to add default plugins, and newly added plugins would have to account for rules it didn't expect. is this causing a problem?

**Comment by vdanchenkov** [comment]
@threepointone Kind of. I had to use two plugins in specific order. And it took some time to figure out why it does not work.

**Comment by vdanchenkov** [comment]
I'm fine with current behaviour if it's documented. It's just something counter-intuitive.

**Comment by threepointone** [comment]
agreed. It'll be part of my docs rewrite. I'll leave this open till that's done.

**Comment by threepointone** [comment]
added to plugins.md, closing this for now
