### ISSUE TITLE
"other" frameworks

### ISSUE THREAD

**Issue by threepointone** [threepointone/glamor#6]
frameworks that use jsx/virtual dom should be able to use this out of the box. however, not sure how to apply these data attributes in angular/ember templates. keeping this issue open to investigate; please help/contribute!

**Comment by threepointone** [comment]
jade was simple; they have an `&attributes(object)` operator that spreads the object onto the element's attributes. 
<img width="317" alt="screen shot 2016-07-24 at 1 50 49 am" src="https://cloud.githubusercontent.com/assets/18808/17080376/325ea9ba-514a-11e6-9a2e-08af6043d33f.png">

**Comment by shrayasr** [comment]
Angular JS comes with `ng-attr-*` and `ng-class`. So usage is something like 

```
<div class="text-center" ng-class="{'text-danger': someBoolValue}">Foobar</div>
```

which would apply the `text-danger` class if `someBoolValue` is `true`

Reference: https://docs.angularjs.org/guide/interpolation

---

ps: Hope this is what you were looking for. I'm slightly new to frontend stuff, so might be wrong

**Comment by treshugart** [comment]
I think for libraries and frameworks that don't use a virtual dom, then there will always be an integration step to sync the changes.

For libraries that don't use JSX, but do use a virtual DOM you can possibly just use `Object.assign()`.

For example, [Skate](https://github.com/skatejs/skatejs) uses [Incremental DOM](https://github.com/google/incremental-dom) and JSX is optional. So you can either:

```js
<div {...style({}) } someattr="test" />
```

Or:

```js
skate.vdom.element('div', Object.assign({}, style({}), { someattr: 'test' }));
```

**Comment by threepointone** [comment]
couldn't figure out ember or angular templates. closing this issue, I think the main ones are covered.

**Comment by threepointone** [comment]
fyi - ember/angular templates can use classname support now, so this is simpler
