### ISSUE TITLE
transition to webpack/CRA/rollup

### ISSUE THREAD

**Issue by threepointone** [threepointone/glamor#62]
we should probably move away from browserify, because fatigue and whatnot.

**Comment by shidhincr** [comment]
@threepointone I would like to take this up. Do you've any preference ?

Webpack ?

**Comment by threepointone** [comment]
Yes, basically replace browserify with webpack, and beefy with webpack-dev-server. Thanks for chipping in!

**Comment by threepointone** [comment]
jumped into this, had to fix the build et al too. it's done, sorry if you already spent time on it!

**Comment by shidhincr** [comment]
Awesome !!! 👏 

I'll try to pick any other open issue .. 👍
