### ISSUE TITLE
Duplicate styles when extracting on server

### ISSUE THREAD

**Issue by KyleAMathews** [threepointone/glamor#64]
https://github.com/gatsbyjs/gatsby/issues/149#issuecomment-251724849

Not a big deal with gzip but still should be fixed at some point.

Also it'd be nice to remove to remove extra whitespace to keep that slick compiled & minified look :-)

**Comment by threepointone** [comment]
Yeah spotted this, will fix asap!

**Comment by threepointone** [comment]
this is fixed and live in 2.16.1. sorry for the trouble!

**Comment by KyleAMathews** [comment]
great! No trouble at all!

**Comment by threepointone** [comment]
ps - I'll do the whitespace fixes in a separate release.

**Comment by KyleAMathews** [comment]
👍

**Comment by threepointone** [comment]
fyi - whitespace fixes live in 2.17.2

**Comment by KyleAMathews** [comment]
Great thanks!

**Comment by cellis** [comment]
I'm still getting this problem, if I inject css into the rendered string AND call `rehydrate`.

**Comment by threepointone** [comment]
could you make sure you're calling rehydrate() before importing any other modules? needs to be at the very start of the app.

**Comment by cellis** [comment]
@threepointone yes this fixed the problem. Thanks
