### ISSUE TITLE
css={} is same as {...style({})}?

### ISSUE THREAD

**Issue by KyleAMathews** [threepointone/glamor#68]
[Correct](https://github.com/threepointone/glamor/blob/59c80356f32938938174d86e0ab1211708c5152a/src/react.js#L15)?

Finding {...merge(` for media queries, pseudo styles to be somewhat cumbersome.

Would rather things just be nested within styles/css

Would rather just write something like:

```
css={{
  lineHeight: 1.3,
  marginBottom: 16,
  [presets.tablet]: {
    marginBottom: 32,
  },
  [presets.hd]: {
    marginBottom: 40,
  },
}}
```

**Comment by threepointone** [comment]
nested pseudo styles work, nested media queries don't work (yet), however yes, css={{}} works. it also accepts arrays, so the following works 
```jsx
css={[{
  lineHeight: 1.3,
  marginBottom: 16,
  ':hover': {
    fontWeight: 'bold'
  }  
}, media(presets.tablet, {
    marginBottom: 32,
  }),
  media(presets.hd, {
    marginBottom: 40,
  })]}
```

I have an open issue for nested media queries, will get to it after my roadtrip.

**Comment by KyleAMathews** [comment]
Ok perfect. Since it accepts arrays that'll hold me over until nested media queries are ready. 💯
