### ISSUE TITLE
CSSPropertyOperations is no longer in react/lib as of 15.4.x

### ISSUE THREAD

**Issue by rszewczyk** [threepointone/glamor#69]
It seems to have moved to `react-dom/lib`

At least as of `15.4.2-rc.2`

**Comment by threepointone** [comment]
ugh, sorry. I'll fix this tomorrow, am on the road right now.

**Comment by threepointone** [comment]
not sure what a clean solution for this is, frankly.

**Comment by threepointone** [comment]
Included a bundled version, released as patch
