### ISSUE TITLE
steal ideas from styled-components

### ISSUE THREAD

**Issue by threepointone** [threepointone/glamor#70]
specifically - 
- string literal notation/interpolated vars 
- inline css syntax (maybe with a babel helper, to be lighter while deploying?)
- RN support 
- 'reusable components' helpers
- etc

**Comment by threepointone** [comment]
got support for 'contextual' selectors in https://github.com/threepointone/glamor/commit/8f35c45f0d397fb0e734b3d430246be744351846

**Comment by threepointone** [comment]
closing this as we've shipped (albeit buggy)

**Comment by chrisdrackett** [comment]
are there docs for this? I'm thinking about using styled-components along with glamor, but if glamor already supports the same syntax that would be wonderful :)
