### ISSUE TITLE
New inlineStyle helper

### ISSUE THREAD

**Issue by calebmer** [threepointone/glamor#74]
For some properties that tend to update quickly in an animation, I get the feeling you shouldn’t be using glamor. Such as a CSS transform. However, some glamor features like autoprefixing would be great to have in such a scenario. Could `glamor` add a helper function named `inlineStyle` or similar that directly applies the styles to JSX nodes instead of adding them to a CSS stylesheet? This could be very helpful for animations.

**Comment by calebmer** [comment]
Or expose the autoprefixing tools, that would be cool too :blush:

Maybe something like: `style={autoprefix({ styles... })}`

**Comment by threepointone** [comment]
`import autoprefix from 'glamor/lib/autoprefix'` should work

**Comment by calebmer** [comment]
Yep :+1:. It’s a named export though so:

```js
import { autoprefix } from 'glamor/lib/autoprefix'
```

Any inclination to make it public :blush:

**Comment by threepointone** [comment]
not really... I might switch it out some time later. I probably won't change the path of this file though, so feel free to use
