### ISSUE TITLE
Prebuilt CSSPropertyOperations.js

### ISSUE THREAD

**Issue by rkurbatov** [threepointone/glamor#82]
Hi there.

Recently our Webpack started to complain with `This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/glamor/lib/CSSPropertyOperations.js 26:78-86`

Not a big deal, but we prefer not to have console warning. Can it be fixed somehow? I tried to put that file to `noParse` section of webpack config as we usually do for such files but this breaks whole bundle.

**Comment by threepointone** [comment]
Can you update your glamor version to the latest and try? We now use our own version of that module.

**Comment by rkurbatov** [comment]
Thanks, working now.
