### ISSUE TITLE
Proposal: Pass template literals instead of object to style()

### ISSUE THREAD

**Issue by sarbbottam** [threepointone/glamor#90]
pass template literals instead of object

```js
let rule = style(`
  // always use hard coded string "selector"
  selector {
    color: 'red',
    & :hover: {
      color: 'pink'
    }
  }

  @media(max-width: 300px) {
    // always use hard coded string "selector"
    selector: {
      color: 'green',
      & :hover: {
        color: 'yellow'
      }
    }
  }
`)
```

- pass this template literal to postCSS to generate CSS
- hashify generated CSS to create dynamic selector name.
- replace hard coded "selector" w/ dynamic selector name returned by hashify
- _rest of the stuff, business as usual_

Benefit:
- leverage postCSS
- let people write the way they write plain old CSS (quite similar to [styled-components](https://github.com/styled-components/styled-components))

Not sure if I am 
- over-simplifying stuff
- reiterating something which has already been thought of

**Comment by threepointone** [comment]
I'm working on a tagged literal version already.

**Comment by threepointone** [comment]
https://twitter.com/threepointone/status/790268053124632576

**Comment by threepointone** [comment]
I'll close this, will ping when I have something to share.

**Comment by sarbbottam** [comment]
Wow, it's like a resonance. I guess glamor is the best thing, happening in CSS in JS.
