### ISSUE TITLE
Glamor logo?

### ISSUE THREAD

**Issue by sarbbottam** [threepointone/glamor#97]
Should there be a glamor logo? I tried creating one, any feedback is appreciated.

![glamor logo](https://cloud.githubusercontent.com/assets/949380/19864909/6d5c426a-9f57-11e6-91d5-ac77dc76d0cb.png)

**Comment by siddharthkp** [comment]
I don't know why, but I thought this emoji was the logo - 💅✨


@threepointone: ?

**Comment by sarbbottam** [comment]
[styled-components](https://github.com/styled-components/styled-components/) uses it.

**Comment by siddharthkp** [comment]
@sarbbottam oops! 😛

**Comment by threepointone** [comment]
I'd like a crack at my own logo if that's alright :) closing this.
